---
title: "Opioid Usage Amongst Behavioural Health Patients: National Trends in the Office Based Prescription of Pain Medications"
output: html_notebook
---

```{r}
## set libraries needed
require(tidyverse)
require(foreign)
require(funModeling)
require(Hmisc)
require(dplyr)
library(tidyr)
require(DataExplorer)
require(readr)
require(tikzDevice)
require(usethis)
library(stringr)
library(goeveg)
```

```{r}
#pull in the datasets from 2006 to 2016
urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2006.tsv"

six <- read.table(url(urlfile), sep = '\t', header = TRUE)

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2007.tsv"

seven <- read.table(url(urlfile), sep = '\t', header = TRUE)

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2008.tsv"

eight <- read.table(url(urlfile), sep = '\t', header = TRUE)

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2009.tsv"

nine <- read.table(url(urlfile), sep = '\t', header = TRUE)

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2010.csv"

ten <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2011.csv"

eleven <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2012.csv"

twelve <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2013.csv"

thirteen <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2014.csv"

fourteen <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2015.csv"

fifteen <- read.csv(url(urlfile))

urlfile="https://raw.githubusercontent.com/keatonpendergrast/bfb/master/2016.csv"

sixteen <- read.csv(url(urlfile))

urlfile="https://raw.githubusercontent.com/keatonpendergrast/bfb/master/2016.csv"

sixteen <- read.csv(url(urlfile))
```

```{r}
#add years to each dataset and select for the columns of interest
sixteen$year <- rep(2016,nrow(sixteen))
sixteen <- sixteen %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)

fifteen$year <- rep(2015,nrow(fifteen))
fifteen <- fifteen %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)

fourteen$year <- rep(2014,nrow(fourteen))
fourteen <- fourteen %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)

thirteen$year <- rep(2013,nrow(thirteen))
thirteen <- thirteen %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)

twelve$year <- rep(2012,nrow(twelve))
twelve <- twelve %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)

eleven$year <- rep(2011,nrow(eleven))
eleven <- eleven %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)

ten$year <- rep(2010,nrow(ten))
ten <- ten %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)

nine$year <- rep(2009,nrow(nine))
nine <- nine %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)

eight$year <- rep(2008,nrow(eight))
eight <- eight %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)

seven$year <- rep(2007,nrow(seven))
seven <- seven %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)

six$year <- rep(2006,nrow(six))
six <- six %>% 
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8)
```

```{r}
#combine all into one big dataset and filter for age
data <- rbind(six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen) %>%
  filter(AGE >= 18)
```

```{r}
#recode the drugs into names
  data[ data == 25530 ] <- "PROPOXYPHENE"
  data[ data == 25530 ] <- "PROPOXYPHENE" 
  data[ data == 25545 ] <- "PROPOXYPHENE" 
  data[ data == 89071 ] <- "PROPOXYPHENE" 
  data[ data == 93411 ] <- "PROPOXYPHENE" 
  data[ data == 25505 ] <- "PROPOXYPHENE" 
  data[ data == 25515 ] <- "PROPOXYPHENE" 
  data[ data == 25520 ] <- "PROPOXYPHENE" 
  data[ data == 41375 ] <- "PROPOXYPHENE" 
  data[ data == 25525 ] <- "PROPOXYPHENE" 
  data[ data == 25510 ] <- "PROPOXYPHENE" 
  data[ data == 02387 ] <- "REMIFENTANIL" 
  data[ data == 10187 ] <- "SUFENTANIL" 
  data[ data == 01187 ] <- "SUFENTANIL" 
  data[ data == 11121 ] <- "TAPENTADOL" 
  data[ data == 02348 ] <- "OXYCODONE" 
  data[ data == 22305 ] <- "OXYCODONE" 
  data[ data == 22306 ] <- "OXYCODONE" 
  data[ data == 28272 ] <- "OXYCODONE" 
  data[ data == 02828 ] <- "OXYCODONE" 
  data[ data == 22307 ] <- "OXYCODONE" 
  data[ data == 22308 ] <- "OXYCODONE" 
  data[ data == 58273 ] <- "OXYCODONE" 
  data[ data == 00389 ] <- "OXYCODONE" 
  data[ data == 08246 ] <- "OXYCODONE" 
  data[ data == 09582 ] <- "OXYCODONE" 
  data[ data == 12028 ] <- "OXYCODONE" 
  data[ data == 22303 ] <- "OXYCODONE" 
  data[ data == 11270 ] <- "OXYMORPHONE" 
  data[ data == 07701 ] <- "PENTAZOCINE" 
  data[ data == 13117 ] <- "PENTAZOCINE" 
  data[ data == 08338 ] <- "PHENEROL" 
  data[ data == 10426 ] <- "MORPHINE" 
  data[ data == 19655 ] <- "MORPHINE" 
  data[ data == 10403 ] <- "MORPHINE" 
  data[ data == 12008 ] <- "MORPHINE" 
  data[ data == 19650 ] <- "MORPHINE" 
  data[ data == 99123 ] <- "MORPHINE" 
  data[ data == 60990 ] <- "NALBUPHINE" 
  data[ data == 11194 ] <- "Narcotic_Analgesics" 
  data[ data == 98067 ] <- "Narcotic_Analgesics" 
  data[ data == 08202 ] <- "OPIUM" 
  data[ data == 21865 ] <- "OPIUM" 
  data[ data == 27380 ] <- "OPIUM" 
  data[ data == 16190 ] <- "OPIUM" 
  data[ data == 17255 ] <- "OPIUM" 
  data[ data == 91084 ] <- "OPIUM" 
  data[ data == 03064 ] <- "OPIUM" 
  data[ data == 09969 ] <- "OPIUM" 
  data[ data == 21860 ] <- "OPIUM" 
  data[ data == 21870 ] <- "OPIUM" 
  data[ data == 21875 ] <- "OPIUM" 
  data[ data == 21880 ] <- "OPIUM" 
  data[ data == 04589 ] <- "OPIUM" 
  data[ data == 22850 ] <- "OPIUM"
  data[ data == 95085 ] <- "MEPERIDINE"
  data[ data == 17340 ] <- "LEVORPHANOL"
  data[ data == 17362 ] <- "LEVORPHANOL"
  data[ data == 08790 ] <- "MEPERIDINE" 
  data[ data == 02943 ] <- "MEPERIDINE" 
  data[ data == 02955 ] <- "MEPERIDINE" 
  data[ data == 95085 ] <- "MEPERIDINE" 
  data[ data == 00200 ] <- "MEPERIDINE" 
  data[ data == 08785 ] <- "MEPERIDINE" 
  data[ data == 12319 ] <- "MEPERIDINE" 
  data[ data == 18760 ] <- "MEPERIDINE" 
  data[ data == 96045 ] <- "MEPERIDINE" 
  data[ data == 01098 ] <- "MEPERIDINE" 
  data[ data == 04534 ] <- "MEPERIDINE" 
  data[ data == 08093 ] <- "MEPERIDINE" 
  data[ data == 18755 ] <- "MEPERIDINE" 
  data[ data == 96012 ] <- "MEPERIDINE" 
  data[ data == 10130 ] <- "METHADONE" 
  data[ data == 18985 ] <- "METHADONE" 
  data[ data == 91012 ] <- "DEZOCINE" 
  data[ data == 91071 ] <- "DEZOCINE" 
  data[ data == 10715 ] <- "DIHYDROCODEINE" 
  data[ data == 00044 ] <- "DIHYDROCODEINE" 
  data[ data == 03078 ] <- "DIHYDROCODEINE" 
  data[ data == 07467 ] <- "DIHYDROCODEINE" 
  data[ data == 11067 ] <- "DIHYDROCODEINE" 
  data[ data == 11184 ] <- "DIHYDROCODEINE"
  data[ data == 93351 ] <- "DIHYDROCODEINE"
  data[ data == 30340 ] <- "DIHYDROCODEINE"
  data[ data == 10128 ] <- "DIHYDROCODEINE"
  data[ data == 40415 ] <- "DIHYDROCODEINE"
  data[ data == 12061 ] <- "DIHYDROCODEINE" 
  data[ data == 09236 ] <- "DIHYDROCODEINE"
  data[ data == 92082 ] <- "DIHYDROCODEINE"
  data[ data == 09574 ] <- "DIHYDROCODEINE" 
  data[ data == 32225 ] <- "DIHYDROCODEINE" 
  data[ data == 27060 ] <- "DIHYDROCODEINE" 
  data[ data == 12173 ] <- "DIHYDROCODEINE" 
  data[ data == 14890 ] <- "DIHYDROCODEINE" 
  data[ data == 15002 ] <- "DIHYDROCODEINE" 
  data[ data == 07225 ] <- "DIHYDROCODEINE" 
  data[ data == 15650 ] <- "FENTANYL" 
  data[ data == 89034 ] <- "FENTANYL" 
  data[ data == 02067 ] <- "FENTANYL" 
  data[ data == 03307 ] <- "FENTANYL" 
  data[ data == 07197 ] <- "FENTANYL" 
  data[ data == 09508 ] <- "FENTANYL" 
  data[ data == 10442 ] <- "FENTANYL" 
  data[ data == 12243 ] <- "FENTANYL" 
  data[ data == 29645 ] <- "FENTANYL" 
  data[ data == 60565 ] <- "FENTANYL" 
  data[ data == 92024 ] <- "FENTANYL" 
  data[ data == 94188 ] <- "FENTANYL" 
  data[ data == 14770 ] <- "HYDROCODONE" 
  data[ data == 92041 ] <- "HYDROCODONE" 
  data[ data == 92042 ] <- "HYDROCODONE" 
  data[ data == 42245 ] <- "HYDROCODONE" 
  data[ data == 06282 ] <- "HYDROCODONE" 
  data[ data == 00251 ] <- "HYDROCODONE" 
  data[ data == 01268 ] <- "HYDROCODONE" 
  data[ data == 01995 ] <- "HYDROCODONE" 
  data[ data == 02045 ] <- "HYDROCODONE" 
  data[ data == 02082 ] <- "HYDROCODONE" 
  data[ data == 02132 ] <- "HYDROCODONE" 
  data[ data == 02314 ] <- "HYDROCODONE" 
  data[ data == 03518 ] <- "HYDROCODONE" 
  data[ data == 06059 ] <- "HYDROCODONE" 
  data[ data == 07064 ] <- "HYDROCODONE" 
  data[ data == 08354 ] <- "HYDROCODONE" 
  data[ data == 10105 ] <- "HYDROCODONE" 
  data[ data == 11162 ] <- "HYDROCODONE" 
  data[ data == 12194 ] <- "HYDROCODONE" 
  data[ data == 14917 ] <- "HYDROCODONE" 
  data[ data == 34110 ] <- "HYDROCODONE" 
  data[ data == 40860 ] <- "HYDROCODONE" 
  data[ data == 60340 ] <- "HYDROCODONE" 
  data[ data == 02045 ] <- "HYDROCODONE"
  data[ data == 89039 ] <- "HYDROCODONE" 
  data[ data == 92180 ] <- "HYDROCODONE" 
  data[ data == 93077 ] <- "HYDROCODONE" 
  data[ data == 93089 ] <- "HYDROCODONE" 
  data[ data == 96028 ] <- "HYDROCODONE" 
  data[ data == 96047 ] <- "HYDROCODONE" 
  data[ data == 98036 ] <- "HYDROCODONE" 
  data[ data == 98168 ] <- "HYDROCODONE" 
  data[ data == 09516 ] <- "HYDROMORPHONE" 
  data[ data == 09595 ] <- "HYDROMORPHONE" 
  data[ data == 09600 ] <- "HYDROMORPHONE" 
  data[ data == 09641 ] <- "HYDROMORPHONE" 
  data[ data == 11229 ] <- "HYDROMORPHONE" 
  data[ data == 15005 ] <- "HYDROMORPHONE" 
  data[ data == 08220 ] <- "HYDROMORPHONE" 
  data[ data == 27315 ] <- "CODEINE" 
  data[ data == 22415 ] <- "CODEINE" 
  data[ data == 11225 ] <- "CODEINE" 
  data[ data == 08910 ] <- "OPIUM" 
  data[ data == 05054 ] <- "BUPRENORPHINE"  
  data[ data == 10386 ] <- "BUPRENORPHINE"
  data[ data == 60265 ] <- "BUPRENORPHINE" 
  data[ data == 10166 ] <- "BUPRENORPHINE" 
  data[ data == 13141 ] <- "BUPRENORPHINE" 
  data[ data == 05103 ] <- "CODEINE" 
  data[ data == 01021 ] <- "BUTORPHANOL" 
  data[ data == 29285 ] <- "BUTORPHANOL" 
  data[ data == 40765 ] <- "CODEINE" 
  data[ data == 11689 ] <- "CODEINE" 
  data[ data == 14014 ] <- "CODEINE" 
  data[ data == 95178 ] <- "CODEINE" 
  data[ data == 13152 ] <- "CODEINE" 
  data[ data == 24143 ] <- "CODEINE" 
  data[ data == 07155 ] <- "CODEINE" 
  data[ data == 07156 ] <- "CODEINE" 
  data[ data == 07157 ] <- "CODEINE" 
  data[ data == 07158 ] <- "CODEINE" 
  data[ data == 07365 ] <- "CODEINE" 
  data[ data == 25880 ] <- "CODEINE" 
  data[ data == 01853 ] <- "CODEINE" 
  data[ data == 28180 ] <- "CODEINE" 
  data[ data == 41260 ] <- "CODEINE" 
  data[ data == 03520 ] <- "CODEINE" 
  data[ data == 00250 ] <- "CODEINE" 
  data[ data == 00265 ] <- "CODEINE" 
  data[ data == 00270 ] <- "CODEINE" 
  data[ data == 00275 ] <- "CODEINE" 
  data[ data == 00280 ] <- "CODEINE" 
  data[ data == 01758 ] <- "CODEINE" 
  data[ data == 02340 ] <- "CODEINE" 
  data[ data == 02345 ] <- "CODEINE" 
  data[ data == 05151 ] <- "CODEINE" 
  data[ data == 05640 ] <- "CODEINE" 
  data[ data == 07080 ] <- "CODEINE" 
  data[ data == 07165 ] <- "CODEINE" 
  data[ data == 07618 ] <- "CODEINE" 
  data[ data == 09538 ] <- "CODEINE" 
  data[ data == 10457 ] <- "CODEINE" 
  data[ data == 11268 ] <- "CODEINE" 
  data[ data == 23665 ] <- "CODEINE" 
  data[ data == 23670 ] <- "CODEINE" 
  data[ data == 23675 ] <- "CODEINE" 
  data[ data == 23680 ] <- "CODEINE" 
  data[ data == 23635 ] <- "CODEINE" 
  data[ data == 28215 ] <- "CODEINE" 
  data[ data == 32910 ] <- "CODEINE" 
  data[ data == 32915 ] <- "CODEINE" 
  data[ data == 32920 ] <- "CODEINE" 
  data[ data == 32930 ] <- "CODEINE" 
  data[ data == 32935 ] <- "CODEINE" 
  data[ data == 41245 ] <- "CODEINE" 
  data[ data == 91010 ] <- "CODEINE" 
  data[ data == 10128 ] <- "DIHYDROCODEINE" 
  data[ data == 40415 ] <- "DIHYDROCODEINE" 
  data[ data == 02730 ] <- "CODEINES" 
  data[ data == 02735 ] <- "CODEINES" 
  data[ data == 02740 ] <- "CODEINE"
  data[ data == 04770 ] <- "CODEINE" 
  data[ data == 12570 ] <- "CODEINE" 
  data[ data == 01028 ] <- "CODEINE" 
  data[ data == 07180 ] <- "CODEINE" 
  data[ data == 07185 ] <- "CODEINE" 
  data[ data == 07190 ] <- "CODEINE" 
  data[ data == 12072 ] <- "CODEINE" 
  data[ data == 92039 ] <- "CODEINE" 
  data[ data == 23790 ] <- "CODEINE" 
  data[ data == 25430 ] <- "CODEINE" 
  data[ data == 12071 ] <- "CODEINE" 
  data[ data == 13028 ] <- "CODEINE" 
  data[ data == 13838 ] <- "CODEINE" 
  data[ data == 13890 ] <- "CODEINE" 
  data[ data == 26835 ] <- "CODEINE" 
  data[ data == 91027 ] <- "CODEINE" 
  data[ data == 32845 ] <- "CODEINE" 
  data[ data == 23798 ] <- "CODEINE" 
  data[ data == 25415 ] <- "CODEINE" 
  data[ data == 25432 ] <- "CODEINE" 
  data[ data == 25359 ] <- "CODEINE" 
  data[ data == 99072 ] <- "CODEINE" 
  data[ data == 91012 ] <- "DEZOCINE" 
  data[ data == 91071 ] <- "DEZOCINE" 
  data[ data == 00866 ] <- "ALFENTANIL" 
  data[ data == 96145 ] <- "ALFENTANIL" 
  data[ data == 21095 ] <- "ALPHAPRODINE" 
  data[ data == 00197 ] <- "DEXTROPROPOXYPHENE" 
  data[ data == 12046 ] <- "OXYCODONE" 
  data[ data == 15062 ] <- "OXYCODONE" 
  data[ data == 22305 ] <- "OXYCODONE" 
  data[ data == 23385 ] <- "OXYCODONE" 
  data[ data == 26958 ] <- "OXYCODONE" 
  data[ data == 32945 ] <- "OXYCODONE" 
  data[ data == 99114 ] <- "OXYCODONE" 
  data[ data == 22308 ] <- "OXYCODONE" 
  data[ data == 12028 ] <- "OXYCODONE" 
  data[ data == 22303 ] <- "OXYCODONE" 
  data[ data == 96109 ] <- "OXYCODONE" 
  data[ data == 97181 ] <- "OXYCODONE" 
  data[ data == 07701 ] <- "PENTAZOCINE" 
  data[ data == 23285 ] <- "PENTAZOCINE" 
  data[ data == 30535 ] <- "PENTAZOCINE" 
  data[ data == 30540 ] <- "PENTAZOCINE" 
  data[ data == 30513 ] <- "PENTAZOCINE"  
  data[ data == 03245 ] <- "OPIUM" 
  data[ data == 21865 ] <- "OPIUM" 
  data[ data == 03276 ] <- "BUPRENORPHINE" 
  data[ data == 10166 ] <- "BUPRENORPHINE" 
  data[ data == 13141 ] <- "BUPRENORPHINE" 
  data[ data == 15650 ] <- "FENTANYL" 
  data[ data == 89034 ] <- "FENTANYL" 
  data[ data == 09737 ] <- "HYDROCODONE" 
  data[ data == 09751 ] <- "HYDROCODONE" 
  data[ data == 10223 ] <- "HYDROCODONE" 
  data[ data == 98043 ] <- "HYDROCODONE" 
  data[ data == 00389 ] <- "OXYCODONE" 
  data[ data == 05040 ] <- "OXYCODONE" 
  data[ data == 01098 ] <- "MEPERIDINE" 
  data[ data == 04534 ] <- "MEPERIDINE" 
  data[ data == 08093 ] <- "MEPERIDINE"
  data[ data == 18755 ] <- "MEPERIDINE" 
  data[ data == 96012 ] <- "MEPERIDINE"
  data[ data == 04538 ] <- "PENTAZOCINE" 
  data[ data == 13117 ] <- "PENTAZOCINE"
  data[ data == 09516 ] <- "HYDROMORPHONE"
```

```{r}
#recode the reasons for visits into categories
data[ data == "11000" ] <- "Anxiety_Nervousness"
data[ data == "11005" ] <- "Fears_Phobias"
data[ data == "11100" ] <- "Depression"
data[ data == "11150" ] <- "Anger"
data[ data == "11200" ] <- "Problems_Identity_Self-esteem"
data[ data == "11250" ] <- "Restlessness"
data[ data == "11300" ] <- "Behavioral_Disturbances"
data[ data == "11301" ] <- "Antisocial_Behavior"
data[ data == "11302" ] <- "Hostile_Behavior"
data[ data == "11303" ] <- "Hysterical_Behavior"
data[ data == "11304" ] <- "Temper_Problems"
data[ data == "11305" ] <- "Obsessions_Compulsions"
data[ data == "11350" ] <- "Disturbances_of_Sleep"
data[ data == "11351" ] <- "Insomnia"
data[ data == "11352" ] <- "Hypersomnia"
data[ data == "11353" ] <- "Nightmares"
data[ data == "11354" ] <- "Sleepwalking"
data[ data == "11355" ] <- "Sleep_Apnea"
data[ data == "11450" ] <- "Alcohol-related_Problems"
data[ data == "11500" ] <- "Abnormal_Drug_Usage"
data[ data == "11501" ] <- "Substance_Abuse"
data[ data == "11550" ] <- "Delusions_or_Hallucinations"
data[ data == "11650" ] <- "Other"
```

```{r}
#everyone on the opioid-controlled substances
data$PATWT <- as.numeric(as.character(data$PATWT)) 

data_1 <- data %>%
  select(year, PATWT, AGE, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8) %>%
  unite(MED, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8) %>%
   mutate(rn = row_number()) %>%
   separate_rows(MED) %>%
   filter(MED %in% c("OXYCODONE", "PROPOXYPHENE", "REMIFENTANIL", "SUFENTANIL", "TAPENTADOL", "OXYMORPHONE", "PHENEROL", "MORPHINE", "NALBUPHINE", "Narcotic_Analgesics", "LEVORPHANOL", "MEPERIDINE", "METHADONE", "DIHYDROCODEINE", "FENTANYL", "OXYCODONE", "HYDROMORPHONE", "OPIUM", "BUPRENORPHINE", "BUTORPHANOL", "CODEINE", "PHENYLPROPANOLAMINE", "DEZOCINE", "ALFENTANIL", "ALPHAPRODINE", "DEXTROPROPOXYPHENE", "PENTAZOCINE")) %>%
   group_by(rn, year, AGE) %>%
   summarise(PATWT = first(PATWT), MED = toString(unique(MED))) %>%
   select(-rn)

summary(data_1)

#combine the combinations
    data_1[ data_1 == "HYDROCODONE, BUPRENORPHINE" ] <- "BUPRENORPHINE, HYDROCODONE"
    data_1[ data_1 == "BUPRENORPHINE, OXYCODONE" ] <- "OXYCODONE, BUPRENORPHINE"
    data_1[ data_1 == "BUTORPHANOL, HYDROCODONE" ] <- "HYDROCODONE, BUTORPHANOL"
    data_1[ data_1 == "BUTORPHANOL, OXYCODONE" ] <- "OXYCODONE, BUTORPHANOL"
    data_1[ data_1 == "BUTORPHANOL, CODEINE" ] <- "CODEINE, BUTORPHANOL"
    data_1[ data_1 == "BUTORPHANOL, MEPERIDINE" ] <- "MEPERIDINE, BUTORPHANOL"
    data_1[ data_1 == "CODEINE, HYDROCODONE" ] <- "HYDROCODONE, CODEINE"
    data_1[ data_1 == "CODEINE, HYDROCODONE, FENTANYL" ] <- "HYDROCODONE, FENTANYL, CODEINE"
    data_1[ data_1 == "CODEINE, HYDROCODONE, HYDROMORPHONE" ] <- "HYDROCODONE, HYDROMORPHONE, CODEINE"
    data_1[ data_1 == "CODEINE, HYDROMORPHONE" ] <- "HYDROMORPHONE, CODEINE"
    data_1[ data_1 == "CODEINE, MEPERIDINE" ] <- "MEPERIDINE, CODEINE"
    data_1[ data_1 == "CODEINE, METHADONE" ] <- "METHADONE, CODEINE"
    data_1[ data_1 == "CODEINE, MORPHINE" ] <- "MORPHINE, CODEINE"
    data_1[ data_1 == "CODEINE, OXYCODONE" ] <- "OXYCODONE, CODEINE"
    data_1[ data_1 == "CODEINE, MORPHINE, OXYCODONE" ] <- "OXYCODONE, MORPHINE, CODEINE"
    data_1[ data_1 == "CODEINE, OPIUM" ] <- "OPIUM, CODEINE"
    data_1[ data_1 == "CODEINE, OXYCODONE" ] <- "OXYCODONE, CODEINE"
    data_1[ data_1 == "CODEINE, OXYCODONE, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, CODEINE"
    data_1[ data_1 == "CODEINE, OXYCODONE, MORPHINE" ] <- "OXYCODONE, MORPHINE, CODEINE"
    data_1[ data_1 == "CODEINE, PENTAZOCINE" ] <- "PENTAZOCINE, CODEINE"
    data_1[ data_1 == "CODEINE, FENTANYL" ] <- "FENTANYL, CODEINE"
    data_1[ data_1 == "CODEINE, PROPOXYPHENE, OXYCODONE" ] <- "OXYCODONE, PROPOXYPHENE, CODEINE"
    data_1[ data_1 == "CODEINE, PROPOXYPHENE" ] <- "PROPOXYPHENE, CODEINE"
    data_1[ data_1 == "DIHYDROCODEINE, HYDROCODONE" ] <- "HYDROCODONE, DIHYDROCODEINE"
    data_1[ data_1 == "DIHYDROCODEINE, OXYCODONE" ] <- "OXYCODONE, DIHYDROCODEINE"
    data_1[ data_1 == "FENTANYL, HYDROCODONE" ] <- "HYDROCODONE, FENTANYL"
    data_1[ data_1 == "FENTANYL, MORPHINE" ] <- "MORPHINE, FENTANYL"
    data_1[ data_1 == "FENTANYL, OXYCODONE" ] <- "OXYCODONE, FENTANYL"
    data_1[ data_1 == "FENTANYL, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, MEPERIDINE, FENTANYL"
    data_1[ data_1 == "FENTANYL, HYDROCODONE, OPIUM" ] <- "HYDROCODONE, FENTANYL, OPIUM"
    data_1[ data_1 == "FENTANYL, HYDROCODONE, OXYCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_1[ data_1 == "FENTANYL, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, FENTANYL"
    data_1[ data_1 == "FENTANYL, HYDROCODONE, MORPHINE" ] <- "HYDROCODONE, MORPHINE, FENTANYL"
    data_1[ data_1 == "FENTANYL, MEPERIDINE" ] <- "MEPERIDINE, FENTANYL"
    data_1[ data_1 == "FENTANYL, OPIUM" ] <- "OPIUM, FENTANYL"
    data_1[ data_1 == "FENTANYL, OXYCODONE, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_1[ data_1 == "FENTANYL, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, FENTANYL"
    data_1[ data_1 == "FENTANYL, METHADONE" ] <- "METHADONE, FENTANYL"
    data_1[ data_1 == "FENTANYL, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, FENTANYL"
    data_1[ data_1 == "FENTANYL, HYDROMORPHONE" ] <- "HYDROMORPHONE, FENTANYL"
    data_1[ data_1 == "FENTANYL, HYDROMORPHONE, MORPHINE" ] <- "HYDROMORPHONE, MORPHINE, FENTANYL"
    data_1[ data_1 == "HYDROCODONE, MORPHINE" ] <- "MORPHINE, HYDROCODONE"
    data_1[ data_1 == "HYDROCODONE, OXYCODONE" ] <- "OXYCODONE, HYDROCODONE"
    data_1[ data_1 == "HYDROCODONE, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, MEPERIDINE, HYDROCODONE"
    data_1[ data_1 == "HYDROCODONE, OPIUM, FENTANYL" ] <- "HYDROCODONE, FENTANYL, OPIUM"
    data_1[ data_1 == "HYDROCODONE, FENTANYL, OXYCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_1[ data_1 == "HYDROCODONE, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, HYDROCODONE"
    data_1[ data_1 == "HYDROCODONE, FENTANYL, MORPHINE" ] <- "HYDROCODONE, MORPHINE, FENTANYL"
    data_1[ data_1 == "HYDROCODONE, MEPERIDINE" ] <- "MEPERIDINE, HYDROCODONE"
    data_1[ data_1 == "HYDROCODONE, OPIUM" ] <- "OPIUM, HYDROCODONE"
    data_1[ data_1 == "HYDROCODONE, OXYCODONE, FENTANYL" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_1[ data_1 == "HYDROCODONE, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, HYDROCODONE"
    data_1[ data_1 == "HYDROCODONE, METHADONE" ] <- "METHADONE, HYDROCODONE"
    data_1[ data_1 == "HYDROCODONE, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, HYDROCODONE"
    data_1[ data_1 == "HYDROCODONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, HYDROCODONE"
    data_1[ data_1 == "HYDROCODONE, HYDROMORPHONE, MORPHINE" ] <- "HYDROCODONE, MORPHINE, HYDROMORPHONE"
    data_1[ data_1 == "HYDROMORPHONE, MORPHINE" ] <- "MORPHINE, HYDROMORPHONE"
    data_1[ data_1 == "HYDROMORPHONE, OXYCODONE" ] <- "OXYCODONE, HYDROMORPHONE"
    data_1[ data_1 == "HYDROMORPHONE, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, HYDROMORPHONE, MEPERIDINE"
    data_1[ data_1 == "HYDROMORPHONE, OPIUM, FENTANYL" ] <- "HYDROMORPHONE, FENTANYL, OPIUM"
    data_1[ data_1 == "HYDROMORPHONE, FENTANYL, OXYCODONE" ] <- "OXYCODONE, HYDROMORPHONE, FENTANYL"
    data_1[ data_1 == "HYDROMORPHONE, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, HYDROMORPHONE"
    data_1[ data_1 == "HYDROMORPHONE, FENTANYL, MORPHINE" ] <- "HYDROMORPHONE, MORPHINE, FENTANYL"
    data_1[ data_1 == "MEPERIDINE, HYDROMORPHONE" ] <- "HYDROMORPHONE, MEPERIDINE"
    data_1[ data_1 == "HYDROMORPHONE, OPIUM" ] <- "OPIUM, HYDROMORPHONE"
    data_1[ data_1 == "HYDROMORPHONE, OXYCODONE, FENTANYL" ] <- "OXYCODONE, HYDROMORPHONE, FENTANYL"
    data_1[ data_1 == "HYDROMORPHONE, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, HYDROMORPHONE"
    data_1[ data_1 == "HYDROMORPHONE, METHADONE" ] <- "METHADONE, HYDROMORPHONE"
    data_1[ data_1 == "HYDROMORPHONE, METHADONE, HYDROCODONE" ] <- "HYDROCODONE, HYDROMORPHONE, METHADONE"
    data_1[ data_1 == "HYDROMORPHONE, HYDROMORPHONE, MORPHINE" ] <- "HYDROMORPHONE, MORPHINE, HYDROMORPHONE"
    data_1[ data_1 == "MEPERIDINE, MORPHINE" ] <- "MORPHINE, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, OXYCODONE" ] <- "OXYCODONE, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, MEPERIDINE, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, OPIUM, FENTANYL" ] <- "FENTANYL, OPIUM, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, FENTANYL, OXYCODONE" ] <- "OXYCODONE, MEPERIDINE, FENTANYL"
    data_1[ data_1 == "MEPERIDINE, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, FENTANYL, MORPHINE" ] <- "MORPHINE, FENTANYL, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, OPIUM" ] <- "OPIUM, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, OXYCODONE, FENTANYL" ] <- "OXYCODONE, FENTANYL, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, METHADONE" ] <- "METHADONE, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, MEPERIDINE"
    data_1[ data_1 == "MEPERIDINE, METHADONE, MORPHINE" ] <- "MORPHINE, METHADONE, MEPERIDINE"
    data_1[ data_1 == "OXYCODONE, MORPHINE" ] <- "MORPHINE, OXYCODONE"
    data_1[ data_1 == "OXYCODONE, HYDROCODONE, MEPERIDINE" ] <- "OXYCODONE, HYDROCODONE, MEPERIDINE"
    data_1[ data_1 == "OXYCODONE, OPIUM, FENTANYL" ] <- "OXYCODONE, FENTANYL, OPIUM"
    data_1[ data_1 == "OXYCODONE, FENTANYL, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_1[ data_1 == "OXYCODONE, METHADONE, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, METHADONE"
    data_1[ data_1 == "OXYCODONE, FENTANYL, MORPHINE" ] <- "OXYCODONE, MORPHINE, FENTANYL"
    data_1[ data_1 == "OXYCODONE, MEPERIDINE" ] <- "MEPERIDINE, OXYCODONE"
    data_1[ data_1 == "OXYCODONE, OPIUM" ] <- "OPIUM, OXYCODONE"
    data_1[ data_1 == "OXYCODONE, HYDROCODONE, FENTANYL" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_1[ data_1 == "OXYCODONE, HYDROCODONE, METHADONE" ] <- "OXYCODONE, HYDROCODONE, METHADONE"
    data_1[ data_1 == "PROPOXYPHENE, OXYCODONE" ] <- "OXYCODONE, PROPOXYPHENE"
    data_1[ data_1 == "METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE"
    data_1[ data_1 == "OXYCODONE, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, OXYCODONE"
    data_1[ data_1 == "OXYCODONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, OXYCODONE"
    data_1[ data_1 == "OXYCODONE, HYDROMORPHONE, MORPHINE" ] <- "OXYCODONE, MORPHINE, HYDROMORPHONE"

  #remove blank entries
data_1[Reduce(`&`, lapply(data_1, function(x) !(is.na(x)|x==""))),]

data_1$AGE[data_1$AGE == "DIHYDROCODEINE"] <- 44
data$AGE[data$AGE == "DIHYDROCODEINE"] <- 44

data_0 <- data_1 %>%
  group_by(year, AGE) %>%
  summarise(sum = sum(PATWT, na.rm=T))

data_0$sum <- as.numeric(as.character(data_0$sum)) 
data_0$AGE <- as.numeric(as.character(data_0$AGE)) 

close0 <- data_0 %>%
  filter(year == 2006) %>%
  mutate(prop = (sum/294180154)*100)
close11 <- data_0 %>%
  filter(year == 2007) %>%
  mutate(prop = (sum/296302408)*100)
close22 <- data_0 %>%
  filter(year == 2008) %>%
  mutate(prop = (sum/298688159)*100)
close33 <- data_0 %>%
  filter(year == 2009) %>%
  mutate(prop = (sum/301570342)*100)
close44 <- data_0 %>%
  filter(year == 2010) %>%
  mutate(prop = (sum/303627880)*100)
close55 <- data_0 %>%
  filter(year == 2011) %>%
  mutate(prop = (sum/306378752)*100)
close66 <- data_0 %>%
  filter(year == 2012) %>%
  mutate(prop = (sum/308698958)*100)
close77 <- data_0 %>%
  filter(year == 2013) %>%
  mutate(prop = (sum/310929426)*100)
close88 <- data_0 %>%
  filter(year == 2014) %>%
  mutate(prop = (sum/313672860)*100)
close99 <- data_0 %>%
  filter(year == 2015) %>%
  mutate(prop = (sum/316286252)*100)
close100 <- data_0 %>%
  filter(year == 2016) %>%
  mutate(prop = (sum/318015317)*100)

data_0summary <- rbind(close0, close11, close22, close33, close44, close55, close66, close77, close88, close99, close100) %>%
  select(year, prop, AGE)
  
write.csv(data_0summary, file = "everyone_on_opioids.csv")

close03 <- data_0 %>%
  filter(year == 2006) %>%
  mutate(prop = 294180154)
close113 <- data_0 %>%
  filter(year == 2007) %>%
  mutate(prop = 296302408)
close223 <- data_0 %>%
  filter(year == 2008) %>%
  mutate(prop = 298688159)
close333 <- data_0 %>%
  filter(year == 2009) %>%
  mutate(prop = 301570342)
close443 <- data_0 %>%
  filter(year == 2010) %>%
  mutate(prop = 303627880)
close553 <- data_0 %>%
  filter(year == 2011) %>%
  mutate(prop = 306378752)
close663 <- data_0 %>%
  filter(year == 2012) %>%
  mutate(prop = 308698958)
close773 <- data_0 %>%
  filter(year == 2013) %>%
  mutate(prop = 310929426)
close883 <- data_0 %>%
  filter(year == 2014) %>%
  mutate(prop = 313672860)
close993 <- data_0 %>%
  filter(year == 2015) %>%
  mutate(prop = 316286252)
close1003 <- data_0 %>%
  filter(year == 2016) %>%
  mutate(prop = 318015317)

data_0summary22 <- rbind(close03, close113, close223, close333, close443, close553, close663, close773, close883, close993, close1003) %>%
  mutate(no = prop) %>%
  mutate(yes = sum) %>%
  select(year, yes, no)

proptest <- pairwise.prop.test(data_0summary22$yes, data_0summary22$no)
proptest

proptrend <- prop.trend.test(data_0summary22$yes, data_0summary22$no)
proptrend
```

```{r}
#behavioural health patients total
new <- data %>%
  select(year, AGE, PATWT, RFV1, RFV2, RFV3) %>%
  unite(RFV, RFV1, RFV2, RFV3) %>%
   mutate(rn = row_number()) %>%
   separate_rows(RFV) %>%
   filter(RFV %in% c("Anxiety_Nervousness", "Fears_Phobias", "Depression", "Anger", "Problems_Identity_Self-esteem", "Restlessness", "Behavioral_Disturbances", "Antisocial_Behavior", "Hostile_Behavior", "Narcotic_Analgesics", "Hysterical_Behavior", "Temper_Problems", "Obsessions_Compulsions", "Disturbances_of_Sleep", "Insomnia", "Hypersomnia", "Nightmares", "Sleepwalking", "Sleep_Apnea", "Alcohol-related_Problems", "Abnormal_Drug_Usage", "Substance_Abuse", "Delusions_or_Hallucinations", "Other"))

new$AGE[new$AGE == "DIHYDROCODEINE"] <- 44
new$AGE <- as.numeric(as.character(new$AGE)) 

new2 <- new %>%
  select(year, PATWT, AGE) %>%
  group_by(year) %>%
  summarise(sum = sum(PATWT, na.rm=T), avg_age = mean(AGE, na.rm=T), sd_age = sem(AGE, na.rm=T))
```

```{r}
# the opioid rate PER year amongst ALL patients BY drug name including AGE
data_1$AGE <- as.numeric(as.character(data_1$AGE))

data_2 <- data_1 %>%
  group_by(year, MED) %>%
  summarise(sum = sum(PATWT, na.rm=T), avg_age = mean(AGE, na.rm=T), sd_age = sem(AGE, na.rm=T))

data_2$sum <- as.numeric(as.character(data_2$sum)) 

sum(six$PATWT)

close0 <- data_2 %>%
  filter(year == 2006) %>%
  mutate(prop = sum/(901954225)*100)
close11 <- data_2 %>%
  filter(year == 2007) %>%
  mutate(prop = (sum/296302408)*100)
close22 <- data_2 %>%
  filter(year == 2008) %>%
  mutate(prop = (sum/298688159)*100)
close33 <- data_2 %>%
  filter(year == 2009) %>%
  mutate(prop = (sum/301570342)*100)
close44 <- data_2 %>%
  filter(year == 2010) %>%
  mutate(prop = (sum/303627880)*100)
close55 <- data_2 %>%
  filter(year == 2011) %>%
  mutate(prop = (sum/306378752)*100)
close66 <- data_2 %>%
  filter(year == 2012) %>%
  mutate(prop = (sum/308698958)*100)
close77 <- data_2 %>%
  filter(year == 2013) %>%
  mutate(prop = (sum/310929426)*100)
close88 <- data_2 %>%
  filter(year == 2014) %>%
  mutate(prop = (sum/313672860)*100)
close99 <- data_2 %>%
  filter(year == 2015) %>%
  mutate(prop = (sum/(316286252))*100)
close100 <- data_2 %>%
  filter(year == 2016) %>%
  mutate(prop = (sum/318015317)*100)

data_2summary <- rbind(close0, close11, close22, close33, close44, close55, close66, close77, close88, close99, close100) %>%
  select(MED, year, prop)

write.csv(data_2summary, file = "data_2summary.csv")

ggplot(data_2summary, aes(year, prop, colour = MED)) + 
  geom_line() +
  theme(legend.position = "none")

library(reshape2)
data_2summary2 <- recast(data_2summary, year + variable ~ MED, id.var = c("MED", "year"))
write.csv(data_2summary2, file = "opioids_all_byname.csv")

ggplot(data_2, aes(year, avg_age, colour = MED)) + 
  geom_line() +
  theme(legend.position = "none")

# the opioid rate PER year amongst ALL patients including AGE
data_2b <- data_1 %>%
  group_by(year) %>%
  summarise(avg_age = mean(AGE, na.rm=T), sd_age = sem(AGE, na.rm=T))

write.csv(data_2b, file = "all_opioid_rate_byage.csv")

# the opioid rate PER year amongst ALL patients including AGE and MED
data_2c <- data_1 %>%
  group_by(year, MED) %>%
  summarise(avg_age = mean(AGE, na.rm=T), sd_age = sem(AGE, na.rm=T))

data_2d <- recast(data_2c, year + variable ~ MED, id.var = c("MED", "year", "sd_age"))

write.csv(data_2d, file = "all_opioid_rate_byage2.csv")

data_2e <- recast(data_2c, year + variable ~ MED, id.var = c("MED", "year", "avg_age"))

write.csv(data_2e, file = "all_opioid_rate_byage3.csv")
```

```{r}
#all patients stats tests by drug

close03a <- data_2 %>%
  filter(year == 2006) %>%
  mutate(prop = 294180154)
close113a <- data_2 %>%
  filter(year == 2007) %>%
  mutate(prop = 296302408)
close223a <- data_2 %>%
  filter(year == 2008) %>%
  mutate(prop = 298688159)
close333a <- data_2 %>%
  filter(year == 2009) %>%
  mutate(prop = 301570342)
close443a <- data_2 %>%
  filter(year == 2010) %>%
  mutate(prop = 303627880)
close553a <- data_2 %>%
  filter(year == 2011) %>%
  mutate(prop = 306378752)
close663a <- data_2 %>%
  filter(year == 2012) %>%
  mutate(prop = 308698958)
close773a <- data_2 %>%
  filter(year == 2013) %>%
  mutate(prop = 310929426)
close883a <- data_2 %>%
  filter(year == 2014) %>%
  mutate(prop = 313672860)
close993a <- data_2 %>%
  filter(year == 2015) %>%
  mutate(prop = 316286252)
close1003a <- data_2 %>%
  filter(year == 2016) %>%
  mutate(prop = 318015317)

data_2summarya <- rbind(close03a, close113a, close223a, close333a, close443a, close553a, close663a, close773a, close883a, close993a, close1003a) %>%
  mutate(no = prop) %>%
  mutate(yes = sum) %>%
  select(year, MED, yes, no)

codeine <- data_2summarya %>%
  filter(MED == "CODEINE")

proptest_cod <- pairwise.prop.test(codeine$yes, codeine$no)
proptest_cod

proptrend_cod <- prop.trend.test(codeine$yes, codeine$no)
proptrend_cod

BUPRENORPHINE <- data_2summarya %>%
  filter(MED == "BUPRENORPHINE")

proptest_bup <- pairwise.prop.test(BUPRENORPHINE$yes, BUPRENORPHINE$no)
proptest_bup

proptrend_bup <- prop.trend.test(BUPRENORPHINE$yes, BUPRENORPHINE$no)
proptrend_bup

FENTANYL <- data_2summarya %>%
  filter(MED == "FENTANYL")

proptest_fen <- pairwise.prop.test(FENTANYL$yes, FENTANYL$no)
proptest_fen

proptrend_fen <- prop.trend.test(FENTANYL$yes, FENTANYL$no)
proptrend_fen

BUTORPHANOL <- data_2summarya %>%
  filter(MED == "BUTORPHANOL")

proptest_but <- pairwise.prop.test(BUTORPHANOL$yes, BUTORPHANOL$no)
proptest_but

proptrend_but <- prop.trend.test(BUTORPHANOL$yes, BUTORPHANOL$no)
proptrend_but

DIHYDROCODEINE <- data_2summarya %>%
  filter(MED == "DIHYDROCODEINE")

proptest_dih <- pairwise.prop.test(DIHYDROCODEINE$yes, DIHYDROCODEINE$no)
proptest_dih

proptrend_dih <- prop.trend.test(DIHYDROCODEINE$yes, DIHYDROCODEINE$no)
proptrend_dih

HYDROMORPHONE <- data_2summarya %>%
  filter(MED == "HYDROMORPHONE")

proptest_hmo <- pairwise.prop.test(HYDROMORPHONE$yes, HYDROMORPHONE$no)
proptest_hmo

proptrend_hmo <- prop.trend.test(HYDROMORPHONE$yes, HYDROMORPHONE$no)
proptrend_hmo

HYDROMORPHONE_FENTANYL <- data_2summarya %>%
  filter(MED == "HYDROMORPHONE, FENTANYL")

proptest_hmf <- pairwise.prop.test(HYDROMORPHONE_FENTANYL$yes, HYDROMORPHONE_FENTANYL$no)
proptest_hmf

proptrend_hmf <- prop.trend.test(HYDROMORPHONE_FENTANYL$yes, HYDROMORPHONE_FENTANYL$no)
proptrend_hmf

MEPERIDINE <- data_2summarya %>%
  filter(MED == "MEPERIDINE")

proptest_mep <- pairwise.prop.test(MEPERIDINE$yes, MEPERIDINE$no)
proptest_mep

proptrend_mep <- prop.trend.test(MEPERIDINE$yes, MEPERIDINE$no)
proptrend_mep

MEPERIDINE_OXYCODONE <- data_2summarya %>%
  filter(MED == "MEPERIDINE, OXYCODONE")

proptest_meo <- pairwise.prop.test(MEPERIDINE_OXYCODONE$yes, MEPERIDINE_OXYCODONE$no)
proptest_meo

proptrend_meo <- prop.trend.test(MEPERIDINE_OXYCODONE$yes, MEPERIDINE_OXYCODONE$no)
proptrend_meo

METHADONE <- data_2summarya %>%
  filter(MED == "METHADONE")

proptest_met <- pairwise.prop.test(METHADONE$yes, METHADONE$no)
proptest_met

proptrend_met <- prop.trend.test(METHADONE$yes, METHADONE$no)
proptrend_met

METHADONE_FENTANYL <- data_2summarya %>%
  filter(MED == "METHADONE, FENTANYL")

proptest_mef <- pairwise.prop.test(METHADONE_FENTANYL$yes, METHADONE_FENTANYL$no)
proptest_mef

proptrend_mef <- prop.trend.test(METHADONE_FENTANYL$yes, METHADONE_FENTANYL$no)
proptrend_mef

METHADONE_HYDROMORPHONE <- data_2summarya %>%
  filter(MED == "METHADONE, HYDROMORPHONE")

proptest_meh <- pairwise.prop.test(METHADONE_HYDROMORPHONE$yes, METHADONE_HYDROMORPHONE$no)
proptest_meh

proptrend_meh <- prop.trend.test(METHADONE_HYDROMORPHONE$yes, METHADONE_HYDROMORPHONE$no)
proptrend_meh

MORPHINE <- data_2summarya %>%
  filter(MED == "MORPHINE")

proptest_mor <- pairwise.prop.test(MORPHINE$yes, MORPHINE$no)
proptest_mor

proptrend_mor <- prop.trend.test(MORPHINE$yes, MORPHINE$no)
proptrend_mor

MORPHINE_FENTANYL <- data_2summarya %>%
  filter(MED == "MORPHINE, FENTANYL")

proptest_mfe <- pairwise.prop.test(MORPHINE_FENTANYL$yes, MORPHINE_FENTANYL$no)
proptest_mfe

proptrend_mfe <- prop.trend.test(MORPHINE_FENTANYL$yes, MORPHINE_FENTANYL$no)
proptrend_mfe

MORPHINE_HYDROMORPHONE <- data_2summarya %>%
  filter(MED == "MORPHINE, HYDROMORPHONE")

proptest_mhy <- pairwise.prop.test(MORPHINE_HYDROMORPHONE$yes, MORPHINE_HYDROMORPHONE$no)
proptest_mhy

proptrend_mhy <- prop.trend.test(MORPHINE_HYDROMORPHONE$yes, MORPHINE_HYDROMORPHONE$no)
proptrend_mhy

OPIUM <- data_2summarya %>%
  filter(MED == "OPIUM")

proptest_opi <- pairwise.prop.test(OPIUM$yes, OPIUM$no)
proptest_opi

proptrend_opi <- prop.trend.test(OPIUM$yes, OPIUM$no)
proptrend_opi

OXYCODONE <- data_2summarya %>%
  filter(MED == "OXYCODONE")

proptest_oxy <- pairwise.prop.test(OXYCODONE$yes, OXYCODONE$no)
proptest_oxy

proptrend_oxy <- prop.trend.test(OXYCODONE$yes, OXYCODONE$no)
proptrend_oxy

OXYCODONE_BUPRENORPHINE <- data_2summarya %>%
  filter(MED == "OXYCODONE, BUPRENORPHINE")

proptest_obu <- pairwise.prop.test(OXYCODONE_BUPRENORPHINE$yes, OXYCODONE_BUPRENORPHINE$no)
proptest_obu

proptrend_obu <- prop.trend.test(OXYCODONE_BUPRENORPHINE$yes, OXYCODONE_BUPRENORPHINE$no)
proptrend_obu

OXYCODONE_CODEINE <- data_2summarya %>%
  filter(MED == "OXYCODONE, CODEINE")

proptest_oco <- pairwise.prop.test(OXYCODONE_CODEINE$yes, OXYCODONE_CODEINE$no)
proptest_oco

proptrend_oco <- prop.trend.test(OXYCODONE_CODEINE$yes, OXYCODONE_CODEINE$no)
proptrend_oco

OXYCODONE_FENTANYL <- data_2summarya %>%
  filter(MED == "OXYCODONE, FENTANYL")

proptest_ofn <- pairwise.prop.test(OXYCODONE_FENTANYL$yes, OXYCODONE_FENTANYL$no)
proptest_ofn

proptrend_ofn <- prop.trend.test(OXYCODONE_FENTANYL$yes, OXYCODONE_FENTANYL$no)
proptrend_ofn

OXYCODONE_METHADONE <- data_2summarya %>%
  filter(MED == "OXYCODONE, METHADONE")

proptest_ome <- pairwise.prop.test(OXYCODONE_METHADONE$yes, OXYCODONE_METHADONE$no)
proptest_ome

proptrend_ome <- prop.trend.test(OXYCODONE_METHADONE$yes, OXYCODONE_METHADONE$no)
proptrend_ome
 
OXYCODONE_PROPOXYPHENE <- data_2summarya %>%
  filter(MED == "OXYCODONE, PROPOXYPHENE")

proptest_opr <- pairwise.prop.test(OXYCODONE_PROPOXYPHENE$yes, OXYCODONE_PROPOXYPHENE$no)
proptest_opr

proptrend_opr <- prop.trend.test(OXYCODONE_PROPOXYPHENE$yes, OXYCODONE_PROPOXYPHENE$no)
proptrend_opr

PENTAZOCINE <- data_2summarya %>%
  filter(MED == "PENTAZOCINE")

proptest_ope <- pairwise.prop.test(PENTAZOCINE$yes, PENTAZOCINE$no)
proptest_ope

proptrend_ope <- prop.trend.test(PENTAZOCINE$yes, PENTAZOCINE$no)
proptrend_ope

PROPOXYPHENE <- data_2summarya %>%
  filter(MED == "PROPOXYPHENE")

proptest_pro <- pairwise.prop.test(PROPOXYPHENE$yes, PROPOXYPHENE$no)
proptest_pro

proptrend_pro <- prop.trend.test(PROPOXYPHENE$yes, PROPOXYPHENE$no)
proptrend_pro

PROPOXYPHENE <- data_2summarya %>%
  filter(MED == "PROPOXYPHENE")

proptest_pro <- pairwise.prop.test(PROPOXYPHENE$yes, PROPOXYPHENE$no)
proptest_pro

proptrend_pro <- prop.trend.test(PROPOXYPHENE$yes, PROPOXYPHENE$no)
proptrend_pro

BUPRENORPHINE <- data_2summarya %>%
  filter(MED == "BUPRENORPHINE")

proptest_bne <- pairwise.prop.test(BUPRENORPHINE$yes, BUPRENORPHINE$no)
proptest_bne

proptrend_bne <- prop.trend.test(BUPRENORPHINE$yes, BUPRENORPHINE$no)
proptrend_bne

BUTORPHANOL <- data_2summarya %>%
  filter(MED == "BUTORPHANOL")

proptest_bnl <- pairwise.prop.test(BUTORPHANOL$yes, BUTORPHANOL$no)
proptest_bnl

proptrend_bnl <- prop.trend.test(BUTORPHANOL$yes, BUTORPHANOL$no)
proptrend_bnl

FENTANYL_CODEINE <- data_2summarya %>%
  filter(MED == "FENTANYL, CODEINE")

proptest_fco <- pairwise.prop.test(FENTANYL_CODEINE$yes, FENTANYL_CODEINE$no)
proptest_fco

proptrend_fco <- prop.trend.test(FENTANYL_CODEINE$yes, FENTANYL_CODEINE$no)
proptrend_fco

HYDROMORPHONE_FENTANYL <- data_2summarya %>%
  filter(MED == "HYDROMORPHONE, FENTANYL")

proptest_hfl <- pairwise.prop.test(HYDROMORPHONE_FENTANYL$yes, HYDROMORPHONE_FENTANYL$no)
proptest_hfl

proptrend_hfl <- prop.trend.test(HYDROMORPHONE_FENTANYL$yes, HYDROMORPHONE_FENTANYL$no)
proptrend_hfl

HYDROMORPHONE_OXYCODONE <- data_2summarya %>%
  filter(MED == "HYDROMORPHONE, OXYCODONE")

proptest_hpo <- pairwise.prop.test(HYDROMORPHONE_OXYCODONE$yes, HYDROMORPHONE_OXYCODONE$no)
proptest_hpo

proptrend_hpo <- prop.trend.test(HYDROMORPHONE_OXYCODONE$yes, HYDROMORPHONE_OXYCODONE$no)
proptrend_hpo
```

```{r}
# the opioid rate PER year amongst ALL patients
data_3 <- data_1 %>%
  group_by(year) %>%
  summarise(sum = sum(PATWT, na.rm=T))

data_3$sum <- as.numeric(as.character(data_3$sum)) 

close0 <- data_3 %>%
  filter(year == 2006) %>%
  mutate(prop = (sum/294180154)*100)
close11 <- data_3 %>%
  filter(year == 2007) %>%
  mutate(prop = (sum/296302408)*100)
close22 <- data_3 %>%
  filter(year == 2008) %>%
  mutate(prop = (sum/298688159)*100)
close33 <- data_3 %>%
  filter(year == 2009) %>%
  mutate(prop = (sum/301570342)*100)
close44 <- data_3 %>%
  filter(year == 2010) %>%
  mutate(prop = (sum/303627880)*100)
close55 <- data_3 %>%
  filter(year == 2011) %>%
  mutate(prop = (sum/306378752)*100)
close66 <- data_3 %>%
  filter(year == 2012) %>%
  mutate(prop = (sum/308698958)*100)
close77 <- data_3 %>%
  filter(year == 2013) %>%
  mutate(prop = (sum/310929426)*100)
close88 <- data_3 %>%
  filter(year == 2014) %>%
  mutate(prop = (sum/313672860)*100)
close99 <- data_3 %>%
  filter(year == 2015) %>%
  mutate(prop = (sum/316286252)*100)
close100 <- data_3 %>%
  filter(year == 2016) %>%
  mutate(prop = (sum/318015317)*100)

data_3summary <- rbind(close0, close11, close22, close33, close44, close55, close66, close77, close88, close99, close100) %>%
  select(year, prop)

write.csv(data_3summary, file = "opioids_rate_all.csv")

ggplot(data_3summary, aes(year, prop)) + 
  geom_line() +
  theme(legend.position = "none")
```

```{r}
# the opioid rate PER year amongst BEHAVIOURAL health patients by MED and RFV
data_4 <- data %>%
  select(year, AGE, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8) %>%
  unite(RFV, RFV1, RFV2, RFV3) %>%
   mutate(rn = row_number()) %>%
   separate_rows(RFV) %>%
   filter(RFV %in% c("Anxiety_Nervousness", "Fears_Phobias", "Depression", "Anger", "Problems_Identity_Self-esteem", "Restlessness", "Behavioral_Disturbances", "Antisocial_Behavior", "Hostile_Behavior", "Narcotic_Analgesics", "Hysterical_Behavior", "Temper_Problems", "Obsessions_Compulsions", "Disturbances_of_Sleep", "Insomnia", "Hypersomnia", "Nightmares", "Sleepwalking", "Sleep_Apnea", "Alcohol-related_Problems", "Abnormal_Drug_Usage", "Substance_Abuse", "Delusions_or_Hallucinations", "Other"))

data_7 <- data_4 %>%
   select(year, AGE, PATWT, RFV, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8) %>%
  unite(MED, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8) %>%
   mutate(rn = row_number()) %>%
   separate_rows(MED) %>%
   filter(MED %in% c("OXYCODONE", "PROPOXYPHENE", "REMIFENTANIL", "SUFENTANIL", "TAPENTADOL", "OXYMORPHONE", "PHENEROL", "MORPHINE", "NALBUPHINE", "Narcotic_Analgesics", "LEVORPHANOL", "MEPERIDINE", "METHADONE", "DIHYDROCODEINE", "FENTANYL", "HYDROCODONE", "HYDROMORPHONE", "OPIUM", "BUPRENORPHINE", "BUTORPHANOL", "CODEINE", "PHENYLPROPANOLAMINE", "DEZOCINE", "ALFENTANIL", "ALPHAPRODINE", "DEXTROPROPOXYPHENE", "", "PENTAZOCINE")) %>%
   group_by(rn, year, AGE, RFV) %>%
   summarise(PATWT = first(PATWT), MED = toString(unique(MED))) %>%
   select(-rn)

#combine the combinations
    data_7[ data_7 == "HYDROCODONE, BUPRENORPHINE" ] <- "BUPRENORPHINE, HYDROCODONE"
    data_7[ data_7 == "BUPRENORPHINE, OXYCODONE" ] <- "OXYCODONE, BUPRENORPHINE"
    data_7[ data_7 == "BUTORPHANOL, HYDROCODONE" ] <- "HYDROCODONE, BUTORPHANOL"
    data_7[ data_7 == "BUTORPHANOL, OXYCODONE" ] <- "OXYCODONE, BUTORPHANOL"
    data_7[ data_7 == "BUTORPHANOL, CODEINE" ] <- "CODEINE, BUTORPHANOL"
    data_7[ data_7 == "BUTORPHANOL, MEPERIDINE" ] <- "MEPERIDINE, BUTORPHANOL"
    data_7[ data_7 == "CODEINE, HYDROCODONE" ] <- "HYDROCODONE, CODEINE"
    data_7[ data_7 == "CODEINE, HYDROCODONE, FENTANYL" ] <- "HYDROCODONE, FENTANYL, CODEINE"
    data_7[ data_7 == "CODEINE, HYDROCODONE, HYDROMORPHONE" ] <- "HYDROCODONE, HYDROMORPHONE, CODEINE"
    data_7[ data_7 == "CODEINE, HYDROMORPHONE" ] <- "HYDROMORPHONE, CODEINE"
    data_7[ data_7 == "CODEINE, MEPERIDINE" ] <- "MEPERIDINE, CODEINE"
    data_7[ data_7 == "CODEINE, METHADONE" ] <- "METHADONE, CODEINE"
    data_7[ data_7 == "CODEINE, MORPHINE" ] <- "MORPHINE, CODEINE"
    data_7[ data_7 == "CODEINE, OXYCODONE" ] <- "OXYCODONE, CODEINE"
    data_7[ data_7 == "CODEINE, MORPHINE, OXYCODONE" ] <- "OXYCODONE, MORPHINE, CODEINE"
    data_7[ data_7 == "CODEINE, OPIUM" ] <- "OPIUM, CODEINE"
    data_7[ data_7 == "CODEINE, OXYCODONE" ] <- "OXYCODONE, CODEINE"
    data_7[ data_7 == "CODEINE, OXYCODONE, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, CODEINE"
    data_7[ data_7 == "CODEINE, OXYCODONE, MORPHINE" ] <- "OXYCODONE, MORPHINE, CODEINE"
    data_7[ data_7 == "CODEINE, PENTAZOCINE" ] <- "PENTAZOCINE, CODEINE"
    data_7[ data_7 == "CODEINE, FENTANYL" ] <- "FENTANYL, CODEINE"
    data_7[ data_7 == "CODEINE, PROPOXYPHENE, OXYCODONE" ] <- "OXYCODONE, PROPOXYPHENE, CODEINE"
    data_7[ data_7 == "CODEINE, PROPOXYPHENE" ] <- "PROPOXYPHENE, CODEINE"
    data_7[ data_7 == "DIHYDROCODEINE, HYDROCODONE" ] <- "HYDROCODONE, DIHYDROCODEINE"
    data_7[ data_7 == "DIHYDROCODEINE, OXYCODONE" ] <- "OXYCODONE, DIHYDROCODEINE"
    data_7[ data_7 == "FENTANYL, HYDROCODONE" ] <- "HYDROCODONE, FENTANYL"
    data_7[ data_7 == "FENTANYL, MORPHINE" ] <- "MORPHINE, FENTANYL"
    data_7[ data_7 == "FENTANYL, OXYCODONE" ] <- "OXYCODONE, FENTANYL"
    data_7[ data_7 == "FENTANYL, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, MEPERIDINE, FENTANYL"
    data_7[ data_7 == "FENTANYL, HYDROCODONE, OPIUM" ] <- "HYDROCODONE, FENTANYL, OPIUM"
    data_7[ data_7 == "FENTANYL, HYDROCODONE, OXYCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_7[ data_7 == "FENTANYL, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, FENTANYL"
    data_7[ data_7 == "FENTANYL, HYDROCODONE, MORPHINE" ] <- "HYDROCODONE, MORPHINE, FENTANYL"
    data_7[ data_7 == "FENTANYL, MEPERIDINE" ] <- "MEPERIDINE, FENTANYL"
    data_7[ data_7 == "FENTANYL, OPIUM" ] <- "OPIUM, FENTANYL"
    data_7[ data_7 == "FENTANYL, OXYCODONE, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_7[ data_7 == "FENTANYL, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, FENTANYL"
    data_7[ data_7 == "FENTANYL, METHADONE" ] <- "METHADONE, FENTANYL"
    data_7[ data_7 == "FENTANYL, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, FENTANYL"
    data_7[ data_7 == "FENTANYL, HYDROMORPHONE" ] <- "HYDROMORPHONE, FENTANYL"
    data_7[ data_7 == "FENTANYL, HYDROMORPHONE, MORPHINE" ] <- "HYDROMORPHONE, MORPHINE, FENTANYL"
    data_7[ data_7 == "HYDROCODONE, MORPHINE" ] <- "MORPHINE, HYDROCODONE"
    data_7[ data_7 == "HYDROCODONE, OXYCODONE" ] <- "OXYCODONE, HYDROCODONE"
    data_7[ data_7 == "HYDROCODONE, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, MEPERIDINE, HYDROCODONE"
    data_7[ data_7 == "HYDROCODONE, OPIUM, FENTANYL" ] <- "HYDROCODONE, FENTANYL, OPIUM"
    data_7[ data_7 == "HYDROCODONE, FENTANYL, OXYCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_7[ data_7 == "HYDROCODONE, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, HYDROCODONE"
    data_7[ data_7 == "HYDROCODONE, FENTANYL, MORPHINE" ] <- "HYDROCODONE, MORPHINE, FENTANYL"
    data_7[ data_7 == "HYDROCODONE, MEPERIDINE" ] <- "MEPERIDINE, HYDROCODONE"
    data_7[ data_7 == "HYDROCODONE, OPIUM" ] <- "OPIUM, HYDROCODONE"
    data_7[ data_7 == "HYDROCODONE, OXYCODONE, FENTANYL" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_7[ data_7 == "HYDROCODONE, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, HYDROCODONE"
    data_7[ data_7 == "HYDROCODONE, METHADONE" ] <- "METHADONE, HYDROCODONE"
    data_7[ data_7 == "HYDROCODONE, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, HYDROCODONE"
    data_7[ data_7 == "HYDROCODONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, HYDROCODONE"
    data_7[ data_7 == "HYDROCODONE, HYDROMORPHONE, MORPHINE" ] <- "HYDROCODONE, MORPHINE, HYDROMORPHONE"
    data_7[ data_7 == "HYDROMORPHONE, MORPHINE" ] <- "MORPHINE, HYDROMORPHONE"
    data_7[ data_7 == "HYDROMORPHONE, OXYCODONE" ] <- "OXYCODONE, HYDROMORPHONE"
    data_7[ data_7 == "HYDROMORPHONE, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, HYDROMORPHONE, MEPERIDINE"
    data_7[ data_7 == "HYDROMORPHONE, OPIUM, FENTANYL" ] <- "HYDROMORPHONE, FENTANYL, OPIUM"
    data_7[ data_7 == "HYDROMORPHONE, FENTANYL, OXYCODONE" ] <- "OXYCODONE, HYDROMORPHONE, FENTANYL"
    data_7[ data_7 == "HYDROMORPHONE, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, HYDROMORPHONE"
    data_7[ data_7 == "HYDROMORPHONE, FENTANYL, MORPHINE" ] <- "HYDROMORPHONE, MORPHINE, FENTANYL"
    data_7[ data_7 == "MEPERIDINE, HYDROMORPHONE" ] <- "HYDROMORPHONE, MEPERIDINE"
    data_7[ data_7 == "HYDROMORPHONE, OPIUM" ] <- "OPIUM, HYDROMORPHONE"
    data_7[ data_7 == "HYDROMORPHONE, OXYCODONE, FENTANYL" ] <- "OXYCODONE, HYDROMORPHONE, FENTANYL"
    data_7[ data_7 == "HYDROMORPHONE, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, HYDROMORPHONE"
    data_7[ data_7 == "HYDROMORPHONE, METHADONE" ] <- "METHADONE, HYDROMORPHONE"
    data_7[ data_7 == "HYDROMORPHONE, METHADONE, HYDROCODONE" ] <- "HYDROCODONE, HYDROMORPHONE, METHADONE"
    data_7[ data_7 == "HYDROMORPHONE, HYDROMORPHONE, MORPHINE" ] <- "HYDROMORPHONE, MORPHINE, HYDROMORPHONE"
    data_7[ data_7 == "MEPERIDINE, MORPHINE" ] <- "MORPHINE, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, OXYCODONE" ] <- "OXYCODONE, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, MEPERIDINE, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, OPIUM, FENTANYL" ] <- "FENTANYL, OPIUM, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, FENTANYL, OXYCODONE" ] <- "OXYCODONE, MEPERIDINE, FENTANYL"
    data_7[ data_7 == "MEPERIDINE, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, FENTANYL, MORPHINE" ] <- "MORPHINE, FENTANYL, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, OPIUM" ] <- "OPIUM, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, OXYCODONE, FENTANYL" ] <- "OXYCODONE, FENTANYL, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, METHADONE" ] <- "METHADONE, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, MEPERIDINE"
    data_7[ data_7 == "MEPERIDINE, METHADONE, MORPHINE" ] <- "MORPHINE, METHADONE, MEPERIDINE"
    data_7[ data_7 == "OXYCODONE, MORPHINE" ] <- "MORPHINE, OXYCODONE"
    data_7[ data_7 == "OXYCODONE, HYDROCODONE, MEPERIDINE" ] <- "OXYCODONE, HYDROCODONE, MEPERIDINE"
    data_7[ data_7 == "OXYCODONE, OPIUM, FENTANYL" ] <- "OXYCODONE, FENTANYL, OPIUM"
    data_7[ data_7 == "OXYCODONE, FENTANYL, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_7[ data_7 == "OXYCODONE, METHADONE, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, METHADONE"
    data_7[ data_7 == "OXYCODONE, FENTANYL, MORPHINE" ] <- "OXYCODONE, MORPHINE, FENTANYL"
    data_7[ data_7 == "OXYCODONE, MEPERIDINE" ] <- "MEPERIDINE, OXYCODONE"
    data_7[ data_7 == "OXYCODONE, OPIUM" ] <- "OPIUM, OXYCODONE"
    data_7[ data_7 == "OXYCODONE, HYDROCODONE, FENTANYL" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_7[ data_7 == "OXYCODONE, HYDROCODONE, METHADONE" ] <- "OXYCODONE, HYDROCODONE, METHADONE"
    data_7[ data_7 == "PROPOXYPHENE, OXYCODONE" ] <- "OXYCODONE, PROPOXYPHENE"
    data_7[ data_7 == "METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE"
    data_7[ data_7 == "OXYCODONE, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, OXYCODONE"
    data_7[ data_7 == "OXYCODONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, OXYCODONE"
    data_7[ data_7 == "OXYCODONE, HYDROMORPHONE, MORPHINE" ] <- "OXYCODONE, MORPHINE, HYDROMORPHONE"

data_7 <- data_7[!(data_7$MED == ""), ]

data_7$AGE <- as.numeric(as.character(data_7$AGE))

data_8 <- data_7 %>%
  group_by(year, MED) %>%
  summarise(sum = sum(PATWT))

data_8b <- data_7 %>%
  group_by(year, MED) %>%
  summarise(sum = sum(PATWT), avg_age = mean(AGE), sd_age = sem(AGE, na.rm=T))

data_8$sum <- as.numeric(as.character(data_8$sum))

close <- data_8 %>%
  filter(year == 2006) %>%
  mutate(prop = sum/(24183976)*100)
close1 <- data_8 %>%
  filter(year == 2007) %>%
  mutate(prop = sum/(28675605)*100)
close2 <- data_8 %>%
  filter(year == 2008) %>%
  mutate(prop = sum/(25519383)*100)
close3 <- data_8 %>%
  filter(year == 2009) %>%
  mutate(prop = sum/(33422924)*100)
close4 <- data_8 %>%
  filter(year == 2010) %>%
  mutate(prop = sum/(22456621)*100)
close5 <- data_8 %>%
  filter(year == 2011) %>%
  mutate(prop = sum/(28939245)*100)
close6 <- data_8 %>%
  filter(year == 2012) %>%
  mutate(prop = sum/(26227511)*100)
close7 <- data_8 %>%
  filter(year == 2013) %>%
  mutate(prop = sum/(29973376)*100)
close8 <- data_8 %>%
  filter(year == 2014) %>%
  mutate(prop = sum/(31435352)*100)
close9 <- data_8 %>%
  filter(year == 2015) %>%
  mutate(prop = sum/(37129324)*100)
close10 <- data_8 %>%
  filter(year == 2016) %>%
  mutate(prop = sum/(22999745)*100)

data_8summary <- rbind(close, close1, close2, close3, close4, close5, close6, close7, close8, close9, close10) %>%
  select(year, prop, MED)

write.csv(data_8summary, file = "data_8summary.csv")

ggplot(data_8summary, aes(year, prop, colour = MED)) + 
  geom_line() +
  theme(legend.position = "none")

data_8summary2 <- recast(data_8summary, year + variable ~ MED, id.var = c("MED", "year"))

write.csv(data_8summary2, file = "mental_opioid_rate_byname.csv")

# the opioid rate PER year amongst MENTAL HEALTH patients including AGE
ggplot(data_8b, aes(year, avg_age, colour = MED)) + 
  geom_line() +
  theme(legend.position = "none")

data_8summary2b <- recast(data_8b, year + variable ~ data_8b$MED, id.var = c("year", "sd_age", "sum", "MED"))

write.csv(data_8summary2b, file = "mental_opioid_rate_byage.csv")

data_8summary2c <- recast(data_8b, year + variable ~ data_8b$MED, id.var = c("year", "sum", "MED", "avg_age"))

write.csv(data_8summary2c, file = "mental_opioid_rate_byage2.csv")

data_8summary2d <- data_7 %>%
  group_by(year, RFV) %>%
  summarise(sum = sum(PATWT))

closek <- data_8summary2d %>%
  filter(year == 2006) %>%
  mutate(prop = sum/(24183976)*100)
close1k <- data_8summary2d %>%
  filter(year == 2007) %>%
  mutate(prop = sum/(28675605)*100)
close2k <- data_8summary2d %>%
  filter(year == 2008) %>%
  mutate(prop = sum/(25519383)*100)
close3k <- data_8summary2d %>%
  filter(year == 2009) %>%
  mutate(prop = sum/(33422924)*100)
close4k <- data_8summary2d %>%
  filter(year == 2010) %>%
  mutate(prop = sum/(22456621)*100)
close5k <- data_8summary2d %>%
  filter(year == 2011) %>%
  mutate(prop = sum/(28939245)*100)
close6k <- data_8summary2d %>%
  filter(year == 2012) %>%
  mutate(prop = sum/(26227511)*100)
close7k <- data_8summary2d %>%
  filter(year == 2013) %>%
  mutate(prop = sum/(29973376)*100)
close8k <- data_8summary2d %>%
  filter(year == 2014) %>%
  mutate(prop = sum/(31435352)*100)
close9k <- data_8summary2d %>%
  filter(year == 2015) %>%
  mutate(prop = sum/(37129324)*100)
close10k <- data_8summary2d %>%
  filter(year == 2016) %>%
  mutate(prop = sum/(22999745)*100)

data_8summary2 <- rbind(closek, close1k, close2k, close3k, close4k, close5k, close6k, close7k, close8k, close9k, close10k) %>%
  select(year, prop, RFV)

data_8summary2e <- recast(data_8summary2, year + variable ~ data_8summary2$RFV, id.var = c("year", "RFV"))

write.csv(data_8summary2e, file = "mental_opioid_rate_byRFV.csv")
```

```{r}
#mental health patients stats tests by drug
close12 <- data_8 %>%
  filter(year == 2006) %>%
  mutate(prop = 24183976)
close112 <- data_8 %>%
  filter(year == 2007) %>%
  mutate(prop = 28675605)
close212 <- data_8 %>%
  filter(year == 2008) %>%
  mutate(prop = 25519383)
close312 <- data_8 %>%
  filter(year == 2009) %>%
  mutate(prop = 33422924)
close412 <- data_8 %>%
  filter(year == 2010) %>%
  mutate(prop = 22456621)
close512 <- data_8 %>%
  filter(year == 2011) %>%
  mutate(prop = 28939245)
close612 <- data_8 %>%
  filter(year == 2012) %>%
  mutate(prop = 26227511)
close712 <- data_8 %>%
  filter(year == 2013) %>%
  mutate(prop = 29973376)
close812 <- data_8 %>%
  filter(year == 2014) %>%
  mutate(prop = 31435352)
close912 <- data_8 %>%
  filter(year == 2015) %>%
  mutate(prop = 37129324)
close1012 <- data_8 %>%
  filter(year == 2016) %>%
  mutate(prop = 22999745)


data_8summary12 <- rbind(close12, close112, close212, close312, close412, close512, close612, close712, close812, close912, close1012) %>%
  mutate(no = prop) %>%
  mutate(yes = sum) %>%
  select(year, MED, yes, no)

codeine2 <- data_8summary12 %>%
  filter(MED == "CODEINE")

proptest_cod2 <- pairwise.prop.test(codeine2$yes, codeine2$no)
proptest_cod2

proptrend_cod2 <- prop.trend.test(codeine2$yes, codeine2$no)
proptrend_cod2

BUPRENORPHINE2 <- data_8summary12 %>%
  filter(MED == "BUPRENORPHINE")

proptest_bup2 <- pairwise.prop.test(BUPRENORPHINE2$yes, BUPRENORPHINE2$no)
proptest_bup2

proptrend_bup2 <- prop.trend.test(BUPRENORPHINE2$yes, BUPRENORPHINE2$no)
proptrend_bup2

FENTANYL2 <- data_8summary12 %>%
  filter(MED == "FENTANYL")

proptest_fen2 <- pairwise.prop.test(FENTANYL2$yes, FENTANYL2$no)
proptest_fen2

proptrend_fen2 <- prop.trend.test(FENTANYL2$yes, FENTANYL2$no)
proptrend_fen2

HYDROMORPHONE2 <- data_8summary12 %>%
  filter(MED == "HYDROMORPHONE")

proptest_hmo2 <- pairwise.prop.test(HYDROMORPHONE2$yes, HYDROMORPHONE2$no)
proptest_hmo2

proptrend_hmo2 <- prop.trend.test(HYDROMORPHONE2$yes, HYDROMORPHONE2$no)
proptrend_hmo2

HYDROMORPHONE_FENTANYL2 <- data_8summary12 %>%
  filter(MED == "HYDROMORPHONE, FENTANYL")

proptest_hmf2 <- pairwise.prop.test(HYDROMORPHONE_FENTANYL2$yes, HYDROMORPHONE_FENTANYL2$no)
proptest_hmf2

proptrend_hmf2 <- prop.trend.test(HYDROMORPHONE_FENTANYL2$yes, HYDROMORPHONE_FENTANYL2$no)
proptrend_hmf2

METHADONE2 <- data_8summary12 %>%
  filter(MED == "METHADONE")

proptest_met2 <- pairwise.prop.test(METHADONE2$yes, METHADONE2$no)
proptest_met2

proptrend_met2 <- prop.trend.test(METHADONE2$yes, METHADONE2$no)
proptrend_met2

MORPHINE2 <- data_8summary12 %>%
  filter(MED == "MORPHINE")

proptest_mor2 <- pairwise.prop.test(MORPHINE2$yes, MORPHINE2$no)
proptest_mor2

proptrend_mor2 <- prop.trend.test(MORPHINE2$yes, MORPHINE2$no)
proptrend_mor2

OPIUM2 <- data_8summary12 %>%
  filter(MED == "OPIUM")

proptest_opi2 <- pairwise.prop.test(OPIUM2$yes, OPIUM2$no)
proptest_opi2

proptrend_opi2 <- prop.trend.test(OPIUM2$yes, OPIUM2$no)
proptrend_opi2

OXYCODONE2 <- data_8summary12 %>%
  filter(MED == "OXYCODONE")

proptest_oxy2 <- pairwise.prop.test(OXYCODONE2$yes, OXYCODONE2$no)
proptest_oxy2

proptrend_oxy2 <- prop.trend.test(OXYCODONE2$yes, OXYCODONE2$no)
proptrend_oxy2

OXYCODONE_CODEINE2 <- data_8summary12 %>%
  filter(MED == "OXYCODONE, CODEINE")

proptest_oco2 <- pairwise.prop.test(OXYCODONE_CODEINE2$yes, OXYCODONE_CODEINE2$no)
proptest_oco2

proptrend_oco2 <- prop.trend.test(OXYCODONE_CODEINE2$yes, OXYCODONE_CODEINE2$no)
proptrend_oco2

OXYCODONE_FENTANYL2 <- data_8summary12 %>%
  filter(MED == "OXYCODONE, FENTANYL")

proptest_ofn2 <- pairwise.prop.test(OXYCODONE_FENTANYL2$yes, OXYCODONE_FENTANYL2$no)
proptest_ofn2

proptrend_ofn2 <- prop.trend.test(OXYCODONE_FENTANYL2$yes, OXYCODONE_FENTANYL2$no)
proptrend_ofn2

OXYCODONE_METHADONE2 <- data_8summary12 %>%
  filter(MED == "OXYCODONE, METHADONE")

proptest_ome2 <- pairwise.prop.test(OXYCODONE_METHADONE2$yes, OXYCODONE_METHADONE2$no)
proptest_ome2

proptrend_ome2 <- prop.trend.test(OXYCODONE_METHADONE2$yes, OXYCODONE_METHADONE2$no)
proptrend_ome2

BUPRENORPHINE2 <- data_8summary12 %>%
  filter(MED == "BUPRENORPHINE")

proptest_bne2 <- pairwise.prop.test(BUPRENORPHINE2$yes, BUPRENORPHINE2$no)
proptest_bne2

proptrend_bne2 <- prop.trend.test(BUPRENORPHINE2$yes, BUPRENORPHINE2$no)
proptrend_bne2

HYDROMORPHONE_FENTANYL2 <- data_8summary12 %>%
  filter(MED == "HYDROMORPHONE, FENTANYL")

proptest_hfl2 <- pairwise.prop.test(HYDROMORPHONE_FENTANYL2$yes, HYDROMORPHONE_FENTANYL2$no)
proptest_hfl2

proptrend_hfl2 <- prop.trend.test(HYDROMORPHONE_FENTANYL2$yes, HYDROMORPHONE_FENTANYL2$no)
proptrend_hfl2

METHADONE_HYDROCODONE2 <- data_8summary12 %>%
  filter(MED == "METHADONE, HYDROCODONE")

proptest_mhd2 <- pairwise.prop.test(METHADONE_HYDROCODONE2$yes, METHADONE_HYDROCODONE2$no)
proptest_mhd2

proptrend_mhd2 <- prop.trend.test(METHADONE_HYDROCODONE2$yes, METHADONE_HYDROCODONE2$no)
proptrend_mhd2

OXYCODONE_HYDROCODONE2 <- data_8summary12 %>%
  filter(MED == "OXYCODONE, HYDROCODONE")

proptest_ohe2 <- pairwise.prop.test(OXYCODONE_HYDROCODONE2$yes, OXYCODONE_HYDROCODONE2$no)
proptest_ohe2

proptrend_ohe2 <- prop.trend.test(OXYCODONE_HYDROCODONE2$yes, OXYCODONE_HYDROCODONE2$no)
proptrend_ohe2

HYDROCODONE_FENTANYL2 <- data_8summary12 %>%
  filter(MED == "HYDROCODONE, FENTANYL")

proptest_hyf2 <- pairwise.prop.test(HYDROCODONE_FENTANYL2$yes, HYDROCODONE_FENTANYL2$no)
proptest_hyf2

proptrend_hyf2 <- prop.trend.test(HYDROCODONE_FENTANYL2$yes, HYDROCODONE_FENTANYL2$no)
proptrend_hyf2
```

```{r}
# the overall opioid rate PER year amongst behavioural health patients ONLY
data_6 <- data_7 %>%
  select(year, PATWT, AGE) %>%
  group_by(year) %>%
  summarise(sum = sum(PATWT, na.rm=T), avg_age = mean(AGE, na.rm=T), sd_age = sem(AGE, na.rm=T))

closea <- data_6 %>%
  filter(year == 2006) %>%
  mutate(prop = sum/(24183976)*100)
closeb <- data_6 %>%
  filter(year == 2007) %>%
  mutate(prop = sum/(28675605)*100)
closec <- data_6 %>%
  filter(year == 2008) %>%
  mutate(prop = sum/(25519383)*100)
closed <- data_6 %>%
  filter(year == 2009) %>%
  mutate(prop = sum/(33422924)*100)
closee <- data_6 %>%
  filter(year == 2010) %>%
  mutate(prop = sum/(22456621)*100)
closef <- data_6 %>%
  filter(year == 2011) %>%
  mutate(prop = sum/(28939245)*100)
closeg<- data_6 %>%
  filter(year == 2012) %>%
  mutate(prop = sum/(26227511)*100)
closeh <- data_6 %>%
  filter(year == 2013) %>%
  mutate(prop = sum/(29973376)*100)
closei <- data_6 %>%
  filter(year == 2014) %>%
  mutate(prop = sum/(31435352)*100)
closej <- data_6 %>%
  filter(year == 2015) %>%
  mutate(prop = sum/(37129324)*100)
closek <- data_6 %>%
  filter(year == 2016) %>%
  mutate(prop = sum/(22999745)*100)

data_6summary <- rbind(closea, closeb, closec, closed, closee, closef, closeg, closeh, closei, closej, closek) %>%
  select(year, prop)

data_6summary$prop <- as.numeric(as.character(data_6summary$prop)) 

write.csv(data_6summary, file = "mental_rate_overall.csv")

scatter.smooth(x=data_6summary$year, y=data_6summary$prop) +
  title(main="Opioid Prescriptions Per Capita")

closeab <- data_6 %>%
  filter(year == 2006) %>%
  mutate(prop = 24183976)
closebb <- data_6 %>%
  filter(year == 2007) %>%
  mutate(prop = 28675605)
closecb <- data_6 %>%
  filter(year == 2008) %>%
  mutate(prop = 25519383)
closedb <- data_6 %>%
  filter(year == 2009) %>%
  mutate(prop = 33422924)
closeeb <- data_6 %>%
  filter(year == 2010) %>%
  mutate(prop = 22456621)
closefb <- data_6 %>%
  filter(year == 2011) %>%
  mutate(prop = 28939245)
closegb <- data_6 %>%
  filter(year == 2012) %>%
  mutate(prop = 26227511)
closehb <- data_6 %>%
  filter(year == 2013) %>%
  mutate(prop = 29973376)
closeib <- data_6 %>%
  filter(year == 2014) %>%
  mutate(prop = 31435352)
closejb <- data_6 %>%
  filter(year == 2015) %>%
  mutate(prop = 37129324)
closekb <- data_6 %>%
  filter(year == 2016) %>%
  mutate(prop = 22999745)

data_6summaryb <- rbind(closeab, closebb, closecb, closedb, closeeb, closefb, closegb, closehb, closeib, closejb, closekb) %>%
  mutate(no = prop) %>%
  mutate(yes = sum) %>%
  select(year, yes, no)

proptest2 <- pairwise.prop.test(data_6summaryb$yes, data_6summaryb$no)
proptest2

proptrend2 <- prop.trend.test(data_6summaryb$yes, data_6summaryb$no)
proptrend2

# the opioid rate PER year amongst MENTAL HEALTH patients by MED including AGE
data_8b <- data_7 %>%
  group_by(year) %>%
  summarise(avg_age = mean(AGE, na.rm=T), sd_age = sem(AGE, na.rm=T))

ggplot(data_6, aes(year, avg_age)) + 
  geom_point() +
  geom_line() +
  theme(legend.position = "none")

write.csv(data_6, file = "mental_opioid_rate_byageonly.csv")
```

```{r}
data_41 <- data %>%
  select(year, PATWT, RFV1, RFV2, RFV3, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8) %>%
  unite(RFV, RFV1, RFV2, RFV3) %>%
   mutate(rn = row_number()) %>%
   separate_rows(RFV) %>%
   filter(RFV %in% c("Anxiety_Nervousness", "Fears_Phobias", "Depression", "Anger", "Problems_Identity_Self-esteem", "Restlessness", "Behavioral_Disturbances", "Antisocial_Behavior", "Hostile_Behavior", "Narcotic_Analgesics", "Hysterical_Behavior", "Temper_Problems", "Obsessions_Compulsions", "Disturbances_of_Sleep", "Insomnia", "Hypersomnia", "Nightmares", "Sleepwalking", "Sleep_Apnea", "Alcohol-related_Problems", "Abnormal_Drug_Usage", "Substance_Abuse", "Delusions_or_Hallucinations", "Other"))

data_71 <- data_41 %>%
   select(year, PATWT, RFV, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8) %>%
  unite(MED, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8) %>%
   mutate(rn = row_number()) %>%
   separate_rows(MED) %>%
   filter(MED %in% c("OXYCODONE", "PROPOXYPHENE", "REMIFENTANIL", "SUFENTANIL", "TAPENTADOL", "OXYMORPHONE", "PHENEROL", "MORPHINE", "NALBUPHINE", "Narcotic_Analgesics", "LEVORPHANOL", "MEPERIDINE", "METHADONE", "DIHYDROCODEINE", "FENTANYL", "HYDROCODONE", "HYDROMORPHONE", "OPIUM", "BUPRENORPHINE", "BUTORPHANOL", "CODEINE", "PHENYLPROPANOLAMINE", "DEZOCINE", "ALFENTANIL", "ALPHAPRODINE", "DEXTROPROPOXYPHENE", "", "PENTAZOCINE")) %>%
   group_by(rn, year, RFV) %>%
   summarise(PATWT = first(PATWT), MED = toString(unique(MED))) %>%
   select(-rn)

#combine the combinations
    data_71[ data_71 == "HYDROCODONE, BUPRENORPHINE" ] <- "BUPRENORPHINE, HYDROCODONE"
    data_71[ data_71 == "BUPRENORPHINE, OXYCODONE" ] <- "OXYCODONE, BUPRENORPHINE"
    data_71[ data_71 == "BUTORPHANOL, HYDROCODONE" ] <- "HYDROCODONE, BUTORPHANOL"
    data_71[ data_71 == "BUTORPHANOL, OXYCODONE" ] <- "OXYCODONE, BUTORPHANOL"
    data_71[ data_71 == "BUTORPHANOL, CODEINE" ] <- "CODEINE, BUTORPHANOL"
    data_71[ data_71 == "BUTORPHANOL, MEPERIDINE" ] <- "MEPERIDINE, BUTORPHANOL"
    data_71[ data_71 == "CODEINE, HYDROCODONE" ] <- "HYDROCODONE, CODEINE"
    data_71[ data_71 == "CODEINE, HYDROCODONE, FENTANYL" ] <- "HYDROCODONE, FENTANYL, CODEINE"
    data_71[ data_71 == "CODEINE, HYDROCODONE, HYDROMORPHONE" ] <- "HYDROCODONE, HYDROMORPHONE, CODEINE"
    data_71[ data_71 == "CODEINE, HYDROMORPHONE" ] <- "HYDROMORPHONE, CODEINE"
    data_71[ data_71 == "CODEINE, MEPERIDINE" ] <- "MEPERIDINE, CODEINE"
    data_71[ data_71 == "CODEINE, METHADONE" ] <- "METHADONE, CODEINE"
    data_71[ data_71 == "CODEINE, MORPHINE" ] <- "MORPHINE, CODEINE"
    data_71[ data_71 == "CODEINE, OXYCODONE" ] <- "OXYCODONE, CODEINE"
    data_71[ data_71 == "CODEINE, MORPHINE, OXYCODONE" ] <- "OXYCODONE, MORPHINE, CODEINE"
    data_71[ data_71 == "CODEINE, OPIUM" ] <- "OPIUM, CODEINE"
    data_71[ data_71 == "CODEINE, OXYCODONE" ] <- "OXYCODONE, CODEINE"
    data_71[ data_71 == "CODEINE, OXYCODONE, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, CODEINE"
    data_71[ data_71 == "CODEINE, OXYCODONE, MORPHINE" ] <- "OXYCODONE, MORPHINE, CODEINE"
    data_71[ data_71 == "CODEINE, PENTAZOCINE" ] <- "PENTAZOCINE, CODEINE"
    data_71[ data_71 == "CODEINE, FENTANYL" ] <- "FENTANYL, CODEINE"
    data_71[ data_71 == "CODEINE, PROPOXYPHENE, OXYCODONE" ] <- "OXYCODONE, PROPOXYPHENE, CODEINE"
    data_71[ data_71 == "CODEINE, PROPOXYPHENE" ] <- "PROPOXYPHENE, CODEINE"
    data_71[ data_71 == "DIHYDROCODEINE, HYDROCODONE" ] <- "HYDROCODONE, DIHYDROCODEINE"
    data_71[ data_71 == "DIHYDROCODEINE, OXYCODONE" ] <- "OXYCODONE, DIHYDROCODEINE"
    data_71[ data_71 == "FENTANYL, HYDROCODONE" ] <- "HYDROCODONE, FENTANYL"
    data_71[ data_71 == "FENTANYL, MORPHINE" ] <- "MORPHINE, FENTANYL"
    data_71[ data_71 == "FENTANYL, OXYCODONE" ] <- "OXYCODONE, FENTANYL"
    data_71[ data_71 == "FENTANYL, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, MEPERIDINE, FENTANYL"
    data_71[ data_71 == "FENTANYL, HYDROCODONE, OPIUM" ] <- "HYDROCODONE, FENTANYL, OPIUM"
    data_71[ data_71 == "FENTANYL, HYDROCODONE, OXYCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_71[ data_71 == "FENTANYL, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, FENTANYL"
    data_71[ data_71 == "FENTANYL, HYDROCODONE, MORPHINE" ] <- "HYDROCODONE, MORPHINE, FENTANYL"
    data_71[ data_71 == "FENTANYL, MEPERIDINE" ] <- "MEPERIDINE, FENTANYL"
    data_71[ data_71 == "FENTANYL, OPIUM" ] <- "OPIUM, FENTANYL"
    data_71[ data_71 == "FENTANYL, OXYCODONE, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_71[ data_71 == "FENTANYL, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, FENTANYL"
    data_71[ data_71 == "FENTANYL, METHADONE" ] <- "METHADONE, FENTANYL"
    data_71[ data_71 == "FENTANYL, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, FENTANYL"
    data_71[ data_71 == "FENTANYL, HYDROMORPHONE" ] <- "HYDROMORPHONE, FENTANYL"
    data_71[ data_71 == "FENTANYL, HYDROMORPHONE, MORPHINE" ] <- "HYDROMORPHONE, MORPHINE, FENTANYL"
    data_71[ data_71 == "HYDROCODONE, MORPHINE" ] <- "MORPHINE, HYDROCODONE"
    data_71[ data_71 == "HYDROCODONE, OXYCODONE" ] <- "OXYCODONE, HYDROCODONE"
    data_71[ data_71 == "HYDROCODONE, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, MEPERIDINE, HYDROCODONE"
    data_71[ data_71 == "HYDROCODONE, OPIUM, FENTANYL" ] <- "HYDROCODONE, FENTANYL, OPIUM"
    data_71[ data_71 == "HYDROCODONE, FENTANYL, OXYCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_71[ data_71 == "HYDROCODONE, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, HYDROCODONE"
    data_71[ data_71 == "HYDROCODONE, FENTANYL, MORPHINE" ] <- "HYDROCODONE, MORPHINE, FENTANYL"
    data_71[ data_71 == "HYDROCODONE, MEPERIDINE" ] <- "MEPERIDINE, HYDROCODONE"
    data_71[ data_71 == "HYDROCODONE, OPIUM" ] <- "OPIUM, HYDROCODONE"
    data_71[ data_71 == "HYDROCODONE, OXYCODONE, FENTANYL" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_71[ data_71 == "HYDROCODONE, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, HYDROCODONE"
    data_71[ data_71 == "HYDROCODONE, METHADONE" ] <- "METHADONE, HYDROCODONE"
    data_71[ data_71 == "HYDROCODONE, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, HYDROCODONE"
    data_71[ data_71 == "HYDROCODONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, HYDROCODONE"
    data_71[ data_71 == "HYDROCODONE, HYDROMORPHONE, MORPHINE" ] <- "HYDROCODONE, MORPHINE, HYDROMORPHONE"
    data_71[ data_71 == "HYDROMORPHONE, MORPHINE" ] <- "MORPHINE, HYDROMORPHONE"
    data_71[ data_71 == "HYDROMORPHONE, OXYCODONE" ] <- "OXYCODONE, HYDROMORPHONE"
    data_71[ data_71 == "HYDROMORPHONE, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, HYDROMORPHONE, MEPERIDINE"
    data_71[ data_71 == "HYDROMORPHONE, OPIUM, FENTANYL" ] <- "HYDROMORPHONE, FENTANYL, OPIUM"
    data_71[ data_71 == "HYDROMORPHONE, FENTANYL, OXYCODONE" ] <- "OXYCODONE, HYDROMORPHONE, FENTANYL"
    data_71[ data_71 == "HYDROMORPHONE, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, HYDROMORPHONE"
    data_71[ data_71 == "HYDROMORPHONE, FENTANYL, MORPHINE" ] <- "HYDROMORPHONE, MORPHINE, FENTANYL"
    data_71[ data_71 == "MEPERIDINE, HYDROMORPHONE" ] <- "HYDROMORPHONE, MEPERIDINE"
    data_71[ data_71 == "HYDROMORPHONE, OPIUM" ] <- "OPIUM, HYDROMORPHONE"
    data_71[ data_71 == "HYDROMORPHONE, OXYCODONE, FENTANYL" ] <- "OXYCODONE, HYDROMORPHONE, FENTANYL"
    data_71[ data_71 == "HYDROMORPHONE, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, HYDROMORPHONE"
    data_71[ data_71 == "HYDROMORPHONE, METHADONE" ] <- "METHADONE, HYDROMORPHONE"
    data_71[ data_71 == "HYDROMORPHONE, METHADONE, HYDROCODONE" ] <- "HYDROCODONE, HYDROMORPHONE, METHADONE"
    data_71[ data_71 == "HYDROMORPHONE, HYDROMORPHONE, MORPHINE" ] <- "HYDROMORPHONE, MORPHINE, HYDROMORPHONE"
    data_71[ data_71 == "MEPERIDINE, MORPHINE" ] <- "MORPHINE, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, OXYCODONE" ] <- "OXYCODONE, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, OXYCODONE, MEPERIDINE" ] <- "OXYCODONE, MEPERIDINE, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, OPIUM, FENTANYL" ] <- "FENTANYL, OPIUM, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, FENTANYL, OXYCODONE" ] <- "OXYCODONE, MEPERIDINE, FENTANYL"
    data_71[ data_71 == "MEPERIDINE, METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, FENTANYL, MORPHINE" ] <- "MORPHINE, FENTANYL, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, OPIUM" ] <- "OPIUM, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, OXYCODONE, FENTANYL" ] <- "OXYCODONE, FENTANYL, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, OXYCODONE, METHADONE" ] <- "OXYCODONE, METHADONE, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, METHADONE" ] <- "METHADONE, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, MEPERIDINE"
    data_71[ data_71 == "MEPERIDINE, METHADONE, MORPHINE" ] <- "MORPHINE, METHADONE, MEPERIDINE"
    data_71[ data_71 == "OXYCODONE, MORPHINE" ] <- "MORPHINE, OXYCODONE"
    data_71[ data_71 == "OXYCODONE, HYDROCODONE, MEPERIDINE" ] <- "OXYCODONE, HYDROCODONE, MEPERIDINE"
    data_71[ data_71 == "OXYCODONE, OPIUM, FENTANYL" ] <- "OXYCODONE, FENTANYL, OPIUM"
    data_71[ data_71 == "OXYCODONE, FENTANYL, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_71[ data_71 == "OXYCODONE, METHADONE, HYDROCODONE" ] <- "OXYCODONE, HYDROCODONE, METHADONE"
    data_71[ data_71 == "OXYCODONE, FENTANYL, MORPHINE" ] <- "OXYCODONE, MORPHINE, FENTANYL"
    data_71[ data_71 == "OXYCODONE, MEPERIDINE" ] <- "MEPERIDINE, OXYCODONE"
    data_71[ data_71 == "OXYCODONE, OPIUM" ] <- "OPIUM, OXYCODONE"
    data_71[ data_71 == "OXYCODONE, HYDROCODONE, FENTANYL" ] <- "OXYCODONE, HYDROCODONE, FENTANYL"
    data_71[ data_71 == "OXYCODONE, HYDROCODONE, METHADONE" ] <- "OXYCODONE, HYDROCODONE, METHADONE"
    data_71[ data_71 == "PROPOXYPHENE, OXYCODONE" ] <- "OXYCODONE, PROPOXYPHENE"
    data_71[ data_71 == "METHADONE, OXYCODONE" ] <- "OXYCODONE, METHADONE"
    data_71[ data_71 == "OXYCODONE, METHADONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, METHADONE, OXYCODONE"
    data_71[ data_71 == "OXYCODONE, HYDROMORPHONE" ] <- "HYDROMORPHONE, OXYCODONE"
    data_71[ data_71 == "OXYCODONE, HYDROMORPHONE, MORPHINE" ] <- "OXYCODONE, MORPHINE, HYDROMORPHONE"

data_71 <- data_71[!(data_71$MED == ""), ]

data_81 <- data_71 %>%
  group_by(year, MED, RFV) %>%
  summarise(sum = sum(PATWT))

data_81$sum <- as.numeric(as.character(data_81$sum)) 

close112 <- data_81 %>%
  filter(year == 2006) %>%
  mutate(prop = sum/(24183976)*100)
close111 <- data_81 %>%
  filter(year == 2007) %>%
  mutate(prop = sum/(28675605)*100)
close211 <- data_81 %>%
  filter(year == 2008) %>%
  mutate(prop = sum/(25519383)*100)
close311 <- data_81 %>%
  filter(year == 2009) %>%
  mutate(prop = sum/(33422924)*100)
close411 <- data_81 %>%
  filter(year == 2010) %>%
  mutate(prop = sum/(22456621)*100)
close511 <- data_81 %>%
  filter(year == 2011) %>%
  mutate(prop = sum/(28939245)*100)
close611 <- data_81 %>%
  filter(year == 2012) %>%
  mutate(prop = sum/(26227511)*100)
close711 <- data_81 %>%
  filter(year == 2013) %>%
  mutate(prop = sum/(29973376)*100)
close811 <- data_81 %>%
  filter(year == 2014) %>%
  mutate(prop = sum/(31435352)*100)
close911 <- data_81 %>%
  filter(year == 2015) %>%
  mutate(prop = sum/(37129324)*100)
close1011 <- data_81 %>%
  filter(year == 2016) %>%
  mutate(prop = sum/(22999745)*100)

data_81summary <- rbind(close112, close111, close211, close311, close411, close511, close611, close711, close811, close911, close1011) %>%
  select(year, prop, MED, RFV)

write.csv(data_81summary, file = "mental_bymed_andRFV.csv")
  
mt <- ggplot(data_81summary, aes(year, prop, colour = factor(MED))) +
  geom_point()

mt + facet_grid(vars(RFV), scales = "free")

library(reshape2)
data_81summary2 <- recast(data_81summary, RFV + variable ~ MED, id.var = c("MED", "RFV"))

write.csv(data_81summary2, file = "mental_bymed_andRFV.csv")

close03ab <- data_81 %>%
  filter(year == 2006) %>%
  mutate(prop = 294180154)
close113ab <- data_81 %>%
  filter(year == 2007) %>%
  mutate(prop = 296302408)
close223ab <- data_81 %>%
  filter(year == 2008) %>%
  mutate(prop = 298688159)
close333ab <- data_81 %>%
  filter(year == 2009) %>%
  mutate(prop = 301570342)
close443ab <- data_81 %>%
  filter(year == 2010) %>%
  mutate(prop = 303627880)
close553ab <- data_81 %>%
  filter(year == 2011) %>%
  mutate(prop = 306378752)
close663ab <- data_81 %>%
  filter(year == 2012) %>%
  mutate(prop = 308698958)
close773ab <- data_81 %>%
  filter(year == 2013) %>%
  mutate(prop = 310929426)
close883ab <- data_81 %>%
  filter(year == 2014) %>%
  mutate(prop = 313672860)
close993ab <- data_81 %>%
  filter(year == 2015) %>%
  mutate(prop = 316286252)
close1003ab <- data_81 %>%
  filter(year == 2016) %>%
  mutate(prop = 318015317)

data_2summaryab <- rbind(close03ab, close113ab, close223ab, close333ab, close443ab, close553ab, close663ab, close773ab, close883ab, close993ab, close1003ab) %>%
  group_by(year, RFV, prop) %>%
  summarise(sum = sum(sum)) %>%
  mutate(yes = sum) %>%
  mutate(no = prop) %>%
  select(year, RFV, yes, no)

Anger <- data_2summaryab %>%
  filter(RFV == "Anger")

proptest_ang <- pairwise.prop.test(Anger$yes, Anger$no)
proptest_ang

proptrend_ang <- prop.trend.test(Anger$yes, Anger$no)
proptrend_ang

Depression <- data_2summaryab %>%
  filter(RFV == "Depression")

proptest_dep <- pairwise.prop.test(Depression$yes, Depression$no)
proptest_dep

proptrend_dep <- prop.trend.test(Depression$yes, Depression $no)
proptrend_dep

Hypersomnia <- data_2summaryab %>%
  filter(RFV == "Hypersomnia")

proptest_hyp <- pairwise.prop.test(Hypersomnia$yes, Hypersomnia$no)
proptest_hyp

proptrend_hyp <- prop.trend.test(Hypersomnia$yes, Hypersomnia $no)
proptrend_hyp

Insomnia <- data_2summaryab %>%
  filter(RFV == "Insomnia")

proptest_ins <- pairwise.prop.test(Insomnia$yes, Insomnia$no)
proptest_ins

proptrend_ins <- prop.trend.test(Insomnia$yes, Insomnia$no)
proptrend_ins

Nightmares <- data_2summaryab %>%
  filter(RFV == "Nightmares")

proptest_nig <- pairwise.prop.test(Nightmares$yes, Nightmares$no)
proptest_nig

proptrend_nig <- prop.trend.test(Nightmares$yes, Nightmares$no)
proptrend_nig

Other <- data_2summaryab %>%
  filter(RFV == "Other")

proptest_oth <- pairwise.prop.test(Other$yes, Other$no)
proptest_oth

proptrend_oth <- prop.trend.test(Other$yes, Other$no)
proptrend_oth

Restlessness <- data_2summaryab %>%
  filter(RFV == "Restlessness")

proptest_res <- pairwise.prop.test(Restlessness$yes, Restlessness$no)
proptest_res

proptrend_res <- prop.trend.test(Restlessness$yes, Restlessness$no)
proptrend_res

Sleepwalking <- data_2summaryab %>%
  filter(RFV == "Sleepwalking")

proptest_sle <- pairwise.prop.test(Sleepwalking$yes, Sleepwalking$no)
proptest_sle

proptrend_sle <- prop.trend.test(Sleepwalking$yes, Sleepwalking$no)
proptrend_sle
```
