---
title: "opioid"
author: "Keaton Pendergrast"
date: "2/13/2020"
output: html_document
---

```{r}
## set libraries needed
require(tidyverse)
require(foreign)
require(funModeling)
require(Hmisc)
require(dplyr)
require(DataExplorer)
require(readr)
require(tikzDevice)
```

```{r}
#pull in the datasets from 2006 to 2016
urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2006.tsv"

six <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2007.tsv"

seven <- read.table(url(urlfile), sep = '\t', header = TRUE)

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2008.tsv"

eight <- read.table(url(urlfile), sep = '\t', header = TRUE)

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2009.tsv"

nine <- read.table(url(urlfile), sep = '\t', header = TRUE)

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2010.csv"

ten <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2011.csv"

eleven <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2012.csv"

twelve <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2013.csv"

thirteen <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2014.csv"

fourteen <- read.csv(url(urlfile))

urlfile="https://media.githubusercontent.com/media/keatonpendergrast/bfb/master/2015.csv"

fifteen <- read.csv(url(urlfile))

urlfile="https://raw.githubusercontent.com/keatonpendergrast/bfb/master/2016.csv"

sixteen <- read.csv(url(urlfile))

urlfile="https://raw.githubusercontent.com/keatonpendergrast/bfb/master/2016.csv"

sixteen <- read.csv(url(urlfile))
```

```{r}
#select for the variables we are interested in
six_clean <- six %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")

seven_clean <- seven %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")
  

eight_clean <- eight %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")

nine_clean <- nine %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")

ten_clean <- ten %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")

eleven_clean <- eleven %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")

twelve_clean <- twelve %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")

thirteen_clean <- thirteen %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")

fourteen_clean <- fourteen %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")

fifteen_clean <- fifteen %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")

sixteen_clean <- sixteen %>%
  select(PHYCODE, PATCODE, SENBEFOR, RFV1, RFV2, RFV3, CONTSUB1, CONTSUB2, CONTSUB3, CONTSUB4, CONTSUB5, CONTSUB6, CONTSUB7, CONTSUB8, MED1, MED2, MED3, MED4, MED5, MED6, MED7, MED8, NCMED1, NCMED2, NCMED3, NCMED4, NCMED5, NCMED6, NCMED7, NCMED8) %>%
  filter(CONTSUB1 == "2" | CONTSUB1 == "3" | CONTSUB1 == "4" | CONTSUB1 == "5" | CONTSUB1 == "8" | CONTSUB2 == "2" | CONTSUB2 == "3" | CONTSUB2 == "4" | CONTSUB2 == "5" | CONTSUB2 == "8" | CONTSUB3 == "2" | CONTSUB3 == "3" | CONTSUB3 == "4" | CONTSUB3 == "5" | CONTSUB3 == "8" | CONTSUB4 == "2" | CONTSUB4 == "3" | CONTSUB4 == "4" | CONTSUB4 == "5" | CONTSUB4 == "8" | CONTSUB5 == "2" | CONTSUB5 == "3" | CONTSUB5 == "4" | CONTSUB5 == "5" | CONTSUB5 == "8" | CONTSUB6 == "2" | CONTSUB6 == "3" | CONTSUB6 == "4" | CONTSUB6 == "5" | CONTSUB6 == "8" | CONTSUB7 == "2" | CONTSUB7 == "3" | CONTSUB7 == "4" | CONTSUB7 == "5" | CONTSUB7 == "8" | CONTSUB8 == "2" | CONTSUB8 == "3" | CONTSUB8 == "4" | CONTSUB8 == "5" | CONTSUB8 == "8")
```

```{r}
sixteen_anx <- sixteen_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")

fifteen_anx <- fifteen_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")

fourteen_anx <- fourteen_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")

thirteen_anx <- thirteen_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")

twelve_anx <- twelve_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")

eleven_anx <- eleven_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")

ten_anx <- ten_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")

nine_anx <- nine_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")

eight_anx <- eight_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")

seven_anx <- seven_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")

six_anx <- six_clean %>%
  filter(RFV1 == "11000" | RFV2 == "11000" | RFV3 == "11000"| RFV1 == "11050" | RFV2 == "11050" | RFV3 == "11050"| RFV1 == "11100" | RFV2 == "11100" | RFV3 == "11100"| RFV1 == "11150" | RFV2 == "11150" | RFV3 == "11150"| RFV1 == "11200" | RFV2 == "11200" | RFV3 == "11200"| RFV1 == "11250" | RFV2 == "11250" | RFV3 == "11250"| RFV1 == "11300" | RFV2 == "11300" | RFV3 == "11300" | RFV1 == "11301" | RFV2 == "11301" | RFV3 == "11301"| RFV1 == "11302" | RFV2 == "11302" | RFV3 == "11302"| RFV1 == "11303" | RFV2 == "11303" | RFV3 == "11303"| RFV1 == "11304" | RFV2 == "11304" | RFV3 == "11304"| RFV1 == "11305" | RFV2 == "11305" | RFV3 == "11305"| RFV1 == "11350" | RFV2 == "11350" | RFV3 == "11350" | RFV1 == "11351" | RFV2 == "11351" | RFV3 == "11351" | RFV1 == "11352" | RFV2 == "11352" | RFV3 == "11352" | RFV1 == "11353" | RFV2 == "11353" | RFV3 == "11353" | RFV1 == "11354" | RFV2 == "11354" | RFV3 == "11354" | RFV1 == "11355" | RFV2 == "11355" | RFV3 == "11355" | RFV1 == "11400" | RFV2 == "11400" | RFV3 == "11400" | RFV1 == "11450" | RFV2 == "11450" | RFV3 == "11450" | RFV1 == "11500" | RFV2 == "11500" | RFV3 == "11500" | RFV1 == "11501" | RFV2 == "11501" | RFV3 == "11501" | RFV1 == "11550" | RFV2 == "11550" | RFV3 == "11550" | RFV1 == "11600" | RFV2 == "11600" | RFV3 == "11600" | RFV1 == "11601" | RFV2 == "11601" | RFV3 == "11601"| RFV1 == "11602" | RFV2 == "11602" | RFV3 == "11602"| RFV1 == "11603" | RFV2 == "11603" | RFV3 == "11603"| RFV1 == "11604" | RFV2 == "11604" | RFV3 == "11604"| RFV1 == "11605" | RFV2 == "11605" | RFV3 == "11605"| RFV1 == "11606" | RFV2 == "11606" | RFV3 == "11606"| RFV1 == "11607" | RFV2 == "11607" | RFV3 == "11607"| RFV1 == "11650" | RFV2 == "11650" | RFV3 == "11650")
```

### Propoxyphene

```{r}

Propoxyphene <- prop_clean %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510")

```

### Remifentanil
```{r}
Remifentanil <- rem_clean %>%
  filter(MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387")
```

### Sufentanil
```{r}
Sufentanil <-suf_clean %>%
  filter(MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187")
```

### Tapentadol

```{r}
Tapentadol <- tap_clean %>%
  filter(MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121")
```

### Oxycodone

```{r}
Oxycodone <- oxy_clean %?%
  filter(MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389" | MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303")
```

### Oxymorphone

```{r}
Oxymorphone <- oxym_clean %>%
   filter(MED1 == "11270" | MED2 == "11270"| MED3 == "11270"| MED4 == "11270"| MED5 == "11270"| MED6 == "11270"| MED7 == "11270" | MED8 == "11270")
  
```

### Pentazocine

```{r}
Pentazocine <- pen_clean %>%
  filter(MED1 == "07701" | MED1 == "13117"| MED1 == "23285"| MED2 == "07701" | MED2 == "13117"| MED2 == "23285"| MED3 == "07701" | MED3 == "13117"| MED3 == "23285"| MED4 == "07701" | MED4 == "13117"| MED4 == "23285"| MED5 == "07701" | MED5 == "13117"| MED5 == "23285"| MED6 == "07701" | MED6 == "13117"| MED6 == "23285"| MED7 == "07701" | MED7 == "13117"| MED7 == "23285"| MED8 == "07701" | MED8 == "13117"| MED8 == "23285")
  
```


### Phenerol

```{r}
Phenerol <- phen_clean%>%
  filter(MED1 == "08338" | MED2 == "08338"| MED3 == "08338"| MED4 == "08338"| MED5 == "08338"| MED6 == "08338"| MED7 == "08338" | MED8 == "08338")
  
```


### Morphine

```{r}
Morphine <- morphine_clean %>%
  filter(MED1 == "10426" | MED1 == "19655"| MED1 == "10403"| MED1 == "12008" | MED1 == "19650"| MED1 == "99123"| MED2 == "10426" | MED2 == "19655"| MED2 == "10403"| MED2 == "12008" | MED2 == "19650"| MED2 == "99123"| MED3 == "10426" | MED3 == "19655"| MED3 == "10403"| MED3 == "12008" | MED3 == "19650"| MED3 == "99123"| MED4 == "10426" | MED4 == "19655"| MED4 == "10403"| MED4 == "12008" | MED4 == "19650"| MED4 == "99123"| MED5 == "10426" | MED5 == "19655"| MED5 == "10403"| MED5 == "12008" | MED5 == "19650"| MED5 == "99123"| MED6 == "10426" | MED6 == "19655"| MED6 == "10403"| MED6 == "12008" | MED6 == "19650"| MED6 == "99123"| MED7 == "10426" | MED7 == "19655"| MED7 == "10403"| MED7 == "12008" | MED7 == "19650"| MED7 == "99123"| MED8 == "10426" | MED8 == "19655"| MED8 == "10403"| MED8 == "12008" | MED8 == "19650"| MED8 == "99123")

```

### Nalbuphine

```{r}
Nalbuphine <-Nal_clean %>%
  filter(MED1 == "60990" | MED2 == "60990"| MED3 == "60990"| MED4 == "60990"| MED5 == "60990"| MED6 == "60990"| MED7 == "60990" | MED8 == "60990")

```

### Narcotic Analgesics

```{r}
NarcoticAnalgesics <-NarAnal_clean %>%
    filter(MED1 == "11194" | MED1 == "98067"| MED2 == "11194"| MED2 == "98067"| MED3 == "11194"| MED3 == "98067"| MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067"| MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067")

  
```

### Opium

```{r}
Opium <- opium_clean %>%
  filter(MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" |MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" |MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" |MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" |MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" |MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```



```{r}
sixteen_drug1 <- sixteen_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```
  
  
```{r}
sixteen_drug2 <- sixteen_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```



```{r}
fifteen_drug1 <- fifteen_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```

```{r}
fifteen_drug2 <- fifteen_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```



```{r}
fourteen_drug1 <- fourteen_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```

```{r}
fourteen_drug2 <- fourteen_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```

```{r}
thirteen_drug1 <- thirteen_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```

```{r}
thirteen_drug2 <- thirteen_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```

```{r}
twelve_drug1 <- twelve_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```

```{r}
twelve_drug2 <- twelve_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```

```{r}
eleven_drug1 <- eleven_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```

```{r}
eleven_drug2 <- eleven_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```

```{r}
ten_drug1 <- ten_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```


```{r}
ten_drug2 <- ten_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```


```{r}
nine_drug1 <- nine_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```


```{r}
nine_drug2 <-nine_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```



```{r}
eight_drug1 <- eight_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```


```{r}
eight_drug2 <-eight_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```


```{r}
seven_drug1 <- seven_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```


```{r}
seven_drug2 <-seven_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```


```{r}
six_drug1 <- six_anx %>%
  filter(MED1 == "25530" | MED1 == "25545" | MED1 == "89071" | MED1 == "89071" | MED1 == "93411" | MED1 == "25505" | MED1 == "25515" | MED1 == "25520" | MED1 == "41375" | MED1 == "25525" | MED1 == "25510" | MED2 == "25530" | MED2 == "25545" | MED2 == "89071" | MED2 == "89071" | MED2 == "93411" | MED2 == "25505" | MED2 == "25515" | MED2 == "25520" | MED2 == "41375" | MED2 == "25525" | MED2 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED3 == "25530" | MED3 == "25545" | MED3 == "89071" | MED3 == "89071" | MED3 == "93411" | MED3 == "25505" | MED3 == "25515" | MED3 == "25520" | MED3 == "41375" | MED3 == "25525" | MED3 == "25510" | MED4 == "25530" | MED4 == "25545" | MED4 == "89071" | MED4 == "89071" | MED4 == "93411" | MED4 == "25505" | MED4 == "25515" | MED4 == "25520" | MED4 == "41375" | MED4 == "25525" | MED4 == "25510" | MED5 == "25530" | MED5 == "25545" | MED5 == "89071" | MED5 == "89071" | MED5 == "93411" | MED5 == "25505" | MED5 == "25515" | MED5 == "25520" | MED5 == "41375" | MED5 == "25525" | MED5 == "25510" | MED6 == "25530" | MED6 == "25545" | MED6 == "89071" | MED6 == "89071" | MED6 == "93411" | MED6 == "25505" | MED6 == "25515" | MED6 == "25520" | MED6 == "41375" | MED6 == "25525" | MED6 == "25510" | MED7 == "25530" | MED7 == "25545" | MED7 == "89071" | MED7 == "89071" | MED7 == "93411" | MED7 == "25505" | MED7 == "25515" | MED7 == "25520" | MED7 == "41375" | MED7 == "25525" | MED7 == "25510" | MED8 == "25530" | MED8 == "25545" | MED8 == "89071" | MED8 == "89071" | MED8 == "93411" | MED8 == "25505" | MED8 == "25515" | MED8 == "25520" | MED8 == "41375" | MED8 == "25525" | MED8 == "25510" | MED1 == "02387" | MED2 == "02387"| MED3 == "02387"| MED4 == "02387"| MED5 == "02387"| MED6 == "02387"| MED7 == "02387" | MED8 == "02387" | MED1 == "10187" | MED1 == "01187" | MED2 == "10187" | MED2 == "01187" | MED3== "10187" | MED3 == "01187" | MED4 == "10187" | MED4 == "01187" | MED5 == "10187" | MED5 == "01187" | MED6 == "10187" | MED6 == "01187" | MED7 == "10187" | MED7 == "01187" |MED8 == "10187" | MED8 == "01187" | MED1 == "11121" | MED2 == "11121"| MED3 == "11121"| MED4 == "11121"| MED5 == "11121"| MED6 == "11121"| MED7 == "11121" | MED8 == "11121" | MED1 == "02348" | MED1 == "22305" | MED1 == "22306" | MED1 == "28272" | MED1 == "02828" | MED1 == "22307" | MED1 == "22308" | MED1 == "58273" | MED1 == "00389" | MED1 == "08246" | MED1 == "09582" |MED1 == "12028" | MED1 == "22303" | MED2 == "02348" | MED2 == "22305" | MED2 == "22306" | MED2 == "28272" | MED2 == "02828" | MED2 == "22307" | MED2 == "22308" | MED2 == "58273" | MED2 == "00389" | MED2 == "08246" | MED2 == "09582" |MED2 == "12028" | MED2 == "22303" | MED3 == "02348" | MED3 == "22305" | MED3 == "22306" | MED3 == "28272" | MED3 == "02828" | MED3 == "22307" | MED3 == "22308" | MED3 == "58273" | MED3 == "00389" | MED3 == "08246" | MED3 == "09582" |MED3 == "12028" | MED3 == "22303" | MED4 == "02348" | MED4 == "22305" | MED4 == "22306" | MED4 == "28272" | MED4 == "02828" | MED4 == "22307" | MED4 == "22308" | MED4 == "58273" | MED4 == "00389" | MED4 == "08246" | MED4 == "09582" |MED4 == "12028" | MED4 == "22303" | MED5 == "02348" | MED5 == "22305" | MED5 == "22306" | MED5 == "28272" | MED5 == "02828" | MED5 == "22307" | MED5 == "22308" | MED5 == "58273" | MED5 == "00389" | MED5 == "08246" | MED5 == "09582" |MED5 == "12028" | MED5 == "22303"| MED6 == "02348" | MED6 == "22305" | MED6 == "22306" | MED6 == "28272" | MED6 == "02828" | MED6 == "22307" | MED6 == "22308" | MED6 == "58273" | MED6 == "00389" | MED6 == "08246" | MED6 == "09582" | MED6 == "12028" | MED6 == "22303" | MED7 == "28272" | MED7 == "02828" | MED7 == "22307" | MED7 == "22308" | MED7 == "58273" | MED7 == "00389" | MED7 == "08246" | MED7 == "09582" |MED7 == "12028" | MED7 == "22303" | MED8 == "02348" | MED8 == "22305" | MED8 == "22306" | MED8 == "28272" | MED8 == "02828" | MED8 == "22307" | MED8 == "22308" | MED8 == "58273" | MED8 == "00389")
```


```{r}
six_drug2 <-six_anx %>%
  filter(MED8 == "08246" | MED8 == "09582" | MED8 == "12028" | MED8 == "22303" | MED1 == "11270" | MED2 == "11270" | MED3 == "11270" | MED4 == "11270" | MED5 == "11270" | MED6 == "11270" | MED7 == "11270" | MED8 == "11270" | MED1 == "07701" | MED1 == "13117" | MED1 == "23285" | MED2 == "07701" | MED2 == "13117" | MED2 == "23285" | MED3 == "07701" | MED3 == "13117" | MED3 == "23285" | MED4 == "07701" | MED4 == "13117" | MED4 == "23285" | MED5 == "07701" | MED5 == "13117" | MED5 == "23285" | MED6 == "07701" | MED6 == "13117" | MED6 == "23285" | MED7 == "07701" | MED7 == "13117" | MED7 == "23285" | MED8 == "07701" | MED8 == "13117" | MED8 == "23285" | MED1 == "08338" | MED2 == "08338" | MED3 == "08338 "| MED4 == "08338" | MED5 == "08338" | MED6 == "08338" | MED7 == "08338" | MED8 == "08338" | MED1 == "10426" | MED1 == "19655" | MED1 == "10403" | MED1 == "12008" | MED1 == "19650" | MED1 == "99123" | MED2 == "10426" | MED2 == "19655" | MED2 == "10403" | MED2 == "12008" | MED2 == "19650" | MED2 == "99123" | MED3 == "10426" | MED3 == "19655" | MED3 == "10403" | MED3 == "12008" | MED3 == "19650" | MED3 == "99123" | MED4 == "10426" | MED4 == "19655" | MED4 == "10403" | MED4 == "12008" | MED4 == "19650" | MED4 == "99123" | MED5 == "10426" | MED5 == "19655" | MED5 == "10403" | MED5 == "12008" | MED5 == "19650" | MED5 == "99123" | MED6 == "10426" | MED6 == "19655" | MED6 == "10403" | MED6 == "12008" | MED6 == "19650" | MED6 == "99123" | MED7 == "10426" | MED7 == "19655" | MED7 == "10403" | MED7 == "12008" | MED7 == "19650" | MED7 == "99123" | MED8 == "10426" | MED8 == "19655" | MED8 == "10403" | MED8 == "12008" | MED8 == "19650" | MED8 == "99123" | MED1 == "60990" | MED2 == "60990" | MED3 == "60990" | MED4 == "60990" | MED5 == "60990" | MED6 == "60990" | MED7 == "60990" | MED8 == "60990" | MED1 == "11194" | MED1 == "98067" | MED2 == "11194" | MED2 == "98067" | MED3 == "11194" | MED3 == "98067" | MED4 == "11194" | MED4 == "98067" | MED5 == "11194" | MED5 == "98067" | MED6 == "11194" | MED6 == "98067" | MED7 == "11194" | MED7 == "98067" | MED8 == "11194" | MED8 == "98067" | MED1 == "08202" | MED1 == "21865" | MED1 == "27380" | MED1 == "16190" | MED1 == "17255" | MED1 == "91084" | MED1 == "03064" | MED1 == "09969" | MED1 == "21860" | MED1 == "21870" | MED1 == "21875" | MED1 == "21880" | MED1 == "04589" | MED2 == "08202" | MED2 == "21865" | MED2 == "27380" | MED2 == "16190" | MED2 == "17255" | MED2 == "91084" | MED2 == "03064" | MED2 == "09969" | MED2 == "21860" | MED2 == "21870" | MED2 == "21875" | MED2 == "21880" | MED2 == "04589" | MED3 == "08202" | MED3 == "21865" | MED3 == "27380" | MED3 == "16190" | MED3 == "17255" | MED3 == "91084" | MED3 == "03064" | MED3 == "09969" | MED3 == "21860" | MED3 == "21870" | MED3 == "21875" | MED3 == "21880" | MED3 == "04589" | MED4 == "08202" | MED4 == "21865" | MED4 == "27380" | MED4 == "16190" | MED4 == "17255" | MED4 == "91084" | MED4 == "03064" | MED4 == "09969" | MED4 == "21860" | MED4 == "21870" | MED4 == "21875" | MED4 == "21880" | MED4 == "04589" | MED5 == "08202" | MED5 == "21865" | MED5 == "27380" | MED5 == "16190" | MED5 == "17255" | MED5 == "91084" | MED5 == "03064" | MED5 == "09969" | MED5 == "21860" | MED5 == "21870" | MED5 == "21875" | MED5 == "21880" | MED5 == "04589" | MED6 == "08202" | MED6 == "21865" | MED6 == "27380" | MED6 == "16190" | MED6 == "17255" | MED6 == "91084" | MED6 == "03064" | MED6 == "09969" | MED6 == "21860" | MED6 == "21870" | MED6 == "21875" | MED6 == "21880" | MED6 == "04589" | MED7 == "08202" | MED7 == "21865" | MED7 == "27380" | MED7 == "16190" | MED7 == "17255" | MED7 == "91084" | MED7 == "03064" | MED7 == "09969" | MED7 == "21860" | MED7 == "21870" | MED7 == "21875" | MED7 == "21880" | MED7 == "04589" | MED8 == "08202" | MED8 == "21865" | MED8 == "27380" | MED8 == "16190" | MED8 == "17255" | MED8 == "91084" | MED8 == "03064" | MED8 == "09969" | MED8 == "21860" | MED8 == "21870" | MED8 == "21875" | MED8 == "21880" | MED8 == "04589")
```

```{r}
sixteen_drug <- rbind(sixteen_drug1, sixteen_drug2)
fifteen_drug <- rbind(fifteen_drug1, fifteen_drug2)
fourteen_drug <- rbind(fourteen_drug1, fourteen_drug2)
thirteen_drug <- rbind(thirteen_drug1, thirteen_drug2)
twelve_drug <- rbind(twelve_drug1, twelve_drug2)
eleven_drug <- rbind(eleven_drug1, eleven_drug2)
ten_drug <- rbind(ten_drug1, ten_drug2)
nine_drug <- rbind(nine_drug1, nine_drug2)
eight_drug <- rbind(eight_drug1, eight_drug2)
seven_drug <- rbind(seven_drug1, seven_drug2)
six_drug <- rbind(six_drug1, six_drug2)
```

```{r}
seven_drug
```


```{r}
plot_str()
```

